C ***********************************************************
C Fortran file translated from WHIRL Fri Oct  5 10:36:31 2007
C ***********************************************************
C ***********************************************************

      MODULE all_globals_mod
      use w2f__types
      use active_module
      IMPLICIT NONE
      SAVE
C
C     **** Statements ****
C
      END MODULE
C ========== begin copyright notice ==============
C This file is part of 
C ---------------
C xaifBooster
C ---------------
C Distributed under the BSD license as follows:
C Copyright (c) 2005, The University of Chicago
C All rights reserved.
C
C Redistribution and use in source and binary forms, 
C with or without modification, are permitted provided that the following conditions are met:
C
C    - Redistributions of source code must retain the above copyright notice, 
C      this list of conditions and the following disclaimer.
C    - Redistributions in binary form must reproduce the above copyright notice, 
C      this list of conditions and the following disclaimer in the documentation 
C      and/or other materials provided with the distribution.
C    - Neither the name of The University of Chicago nor the names of its contributors 
C      may be used to endorse or promote products derived from this software without 
C      specific prior written permission.
C
C THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
C EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
C OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
C SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
C INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
C PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
C INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
C LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
C OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
C 
C General Information:
C xaifBooster is intended for the transformation of 
C numerical programs represented as xml files according 
C to the XAIF schema. It is part of the OpenAD framework. 
C The main application is automatic 
C differentiation, i.e. the generation of code for 
C the computation of derivatives. 
C The following people are the principal authors of the 
C current version: 
C 	Uwe Naumann
C	Jean Utke
C Additional contributors are: 
C	Andrew Lyons
C	Peter Fine
C
C For more details about xaifBooster and its use in OpenAD please visit:
C   http://www.mcs.anl.gov/openad
C
C This work is partially supported by:
C 	NSF-ITR grant OCE-0205590
C ========== end copyright notice ==============
       subroutine head(NX,NY,X,FVEC,R)
          use OpenAD_dct
          use OpenAD_tape
          use OpenAD_rev
          use OpenAD_checkpoints

          ! original arguments get inserted before version
          ! and declared here together with all local variables
          ! generated by xaifBooster

      use w2f__types
      use active_module
      IMPLICIT NONE
C
C     **** Global Variables & Derived Type Definitions ****
C
      REAL(w2f__8) OpenAD_Symbol_0
      REAL(w2f__8) OpenAD_Symbol_1
      REAL(w2f__8) OpenAD_Symbol_10
      REAL(w2f__8) OpenAD_Symbol_101
      REAL(w2f__8) OpenAD_Symbol_102
      REAL(w2f__8) OpenAD_Symbol_103
      REAL(w2f__8) OpenAD_Symbol_104
      REAL(w2f__8) OpenAD_Symbol_105
      REAL(w2f__8) OpenAD_Symbol_107
      REAL(w2f__8) OpenAD_Symbol_108
      REAL(w2f__8) OpenAD_Symbol_11
      REAL(w2f__8) OpenAD_Symbol_110
      REAL(w2f__8) OpenAD_Symbol_111
      REAL(w2f__8) OpenAD_Symbol_112
      REAL(w2f__8) OpenAD_Symbol_113
      REAL(w2f__8) OpenAD_Symbol_114
      REAL(w2f__8) OpenAD_Symbol_116
      REAL(w2f__8) OpenAD_Symbol_117
      REAL(w2f__8) OpenAD_Symbol_118
      REAL(w2f__8) OpenAD_Symbol_119
      REAL(w2f__8) OpenAD_Symbol_12
      REAL(w2f__8) OpenAD_Symbol_120
      REAL(w2f__8) OpenAD_Symbol_121
      REAL(w2f__8) OpenAD_Symbol_122
      REAL(w2f__8) OpenAD_Symbol_124
      REAL(w2f__8) OpenAD_Symbol_125
      REAL(w2f__8) OpenAD_Symbol_126
      REAL(w2f__8) OpenAD_Symbol_127
      REAL(w2f__8) OpenAD_Symbol_128
      REAL(w2f__8) OpenAD_Symbol_13
      REAL(w2f__8) OpenAD_Symbol_130
      REAL(w2f__8) OpenAD_Symbol_131
      REAL(w2f__8) OpenAD_Symbol_133
      REAL(w2f__8) OpenAD_Symbol_134
      REAL(w2f__8) OpenAD_Symbol_135
      REAL(w2f__8) OpenAD_Symbol_136
      REAL(w2f__8) OpenAD_Symbol_137
      REAL(w2f__8) OpenAD_Symbol_139
      REAL(w2f__8) OpenAD_Symbol_14
      REAL(w2f__8) OpenAD_Symbol_141
      REAL(w2f__8) OpenAD_Symbol_142
      REAL(w2f__8) OpenAD_Symbol_143
      REAL(w2f__8) OpenAD_Symbol_144
      REAL(w2f__8) OpenAD_Symbol_145
      REAL(w2f__8) OpenAD_Symbol_146
      REAL(w2f__8) OpenAD_Symbol_148
      REAL(w2f__8) OpenAD_Symbol_149
      REAL(w2f__8) OpenAD_Symbol_15
      REAL(w2f__8) OpenAD_Symbol_150
      REAL(w2f__8) OpenAD_Symbol_151
      REAL(w2f__8) OpenAD_Symbol_152
      REAL(w2f__8) OpenAD_Symbol_153
      REAL(w2f__8) OpenAD_Symbol_154
      REAL(w2f__8) OpenAD_Symbol_155
      REAL(w2f__8) OpenAD_Symbol_157
      REAL(w2f__8) OpenAD_Symbol_158
      REAL(w2f__8) OpenAD_Symbol_159
      REAL(w2f__8) OpenAD_Symbol_160
      REAL(w2f__8) OpenAD_Symbol_161
      REAL(w2f__8) OpenAD_Symbol_162
      type(active) :: OpenAD_Symbol_163
      type(active) :: OpenAD_Symbol_164
      type(active) :: OpenAD_Symbol_165
      type(active) :: OpenAD_Symbol_166
      type(active) :: OpenAD_Symbol_167
      REAL(w2f__8) OpenAD_Symbol_168
      REAL(w2f__8) OpenAD_Symbol_169
      REAL(w2f__8) OpenAD_Symbol_17
      REAL(w2f__8) OpenAD_Symbol_170
      REAL(w2f__8) OpenAD_Symbol_171
      REAL(w2f__8) OpenAD_Symbol_172
      REAL(w2f__8) OpenAD_Symbol_173
      REAL(w2f__8) OpenAD_Symbol_174
      REAL(w2f__8) OpenAD_Symbol_175
      REAL(w2f__8) OpenAD_Symbol_176
      REAL(w2f__8) OpenAD_Symbol_177
      REAL(w2f__8) OpenAD_Symbol_178
      REAL(w2f__8) OpenAD_Symbol_179
      REAL(w2f__8) OpenAD_Symbol_18
      REAL(w2f__8) OpenAD_Symbol_180
      REAL(w2f__8) OpenAD_Symbol_181
      REAL(w2f__8) OpenAD_Symbol_182
      REAL(w2f__8) OpenAD_Symbol_183
      REAL(w2f__8) OpenAD_Symbol_184
      REAL(w2f__8) OpenAD_Symbol_185
      REAL(w2f__8) OpenAD_Symbol_186
      REAL(w2f__8) OpenAD_Symbol_187
      REAL(w2f__8) OpenAD_Symbol_188
      REAL(w2f__8) OpenAD_Symbol_189
      REAL(w2f__8) OpenAD_Symbol_19
      REAL(w2f__8) OpenAD_Symbol_190
      REAL(w2f__8) OpenAD_Symbol_191
      REAL(w2f__8) OpenAD_Symbol_192
      REAL(w2f__8) OpenAD_Symbol_193
      REAL(w2f__8) OpenAD_Symbol_194
      REAL(w2f__8) OpenAD_Symbol_195
      REAL(w2f__8) OpenAD_Symbol_196
      REAL(w2f__8) OpenAD_Symbol_197
      REAL(w2f__8) OpenAD_Symbol_198
      REAL(w2f__8) OpenAD_Symbol_199
      REAL(w2f__8) OpenAD_Symbol_2
      REAL(w2f__8) OpenAD_Symbol_20
      REAL(w2f__8) OpenAD_Symbol_200
      REAL(w2f__8) OpenAD_Symbol_201
      REAL(w2f__8) OpenAD_Symbol_202
      REAL(w2f__8) OpenAD_Symbol_203
      REAL(w2f__8) OpenAD_Symbol_204
      REAL(w2f__8) OpenAD_Symbol_205
      REAL(w2f__8) OpenAD_Symbol_206
      type(active) :: OpenAD_Symbol_207
      REAL(w2f__8) OpenAD_Symbol_208
      REAL(w2f__8) OpenAD_Symbol_209
      REAL(w2f__8) OpenAD_Symbol_21
      type(active) :: OpenAD_Symbol_210
      REAL(w2f__8) OpenAD_Symbol_211
      REAL(w2f__8) OpenAD_Symbol_212
      REAL(w2f__8) OpenAD_Symbol_213
      type(active) :: OpenAD_Symbol_214
      REAL(w2f__8) OpenAD_Symbol_215
      REAL(w2f__8) OpenAD_Symbol_216
      type(active) :: OpenAD_Symbol_217
      REAL(w2f__8) OpenAD_Symbol_218
      REAL(w2f__8) OpenAD_Symbol_219
      REAL(w2f__8) OpenAD_Symbol_220
      type(active) :: OpenAD_Symbol_221
      REAL(w2f__8) OpenAD_Symbol_222
      REAL(w2f__8) OpenAD_Symbol_223
      REAL(w2f__8) OpenAD_Symbol_224
      REAL(w2f__8) OpenAD_Symbol_225
      REAL(w2f__8) OpenAD_Symbol_226
      REAL(w2f__8) OpenAD_Symbol_227
      REAL(w2f__8) OpenAD_Symbol_228
      type(active) :: OpenAD_Symbol_229
      REAL(w2f__8) OpenAD_Symbol_23
      REAL(w2f__8) OpenAD_Symbol_230
      REAL(w2f__8) OpenAD_Symbol_231
      REAL(w2f__8) OpenAD_Symbol_232
      type(active) :: OpenAD_Symbol_233
      REAL(w2f__8) OpenAD_Symbol_234
      REAL(w2f__8) OpenAD_Symbol_235
      type(active) :: OpenAD_Symbol_236
      REAL(w2f__8) OpenAD_Symbol_237
      REAL(w2f__8) OpenAD_Symbol_238
      REAL(w2f__8) OpenAD_Symbol_239
      REAL(w2f__8) OpenAD_Symbol_24
      type(active) :: OpenAD_Symbol_240
      REAL(w2f__8) OpenAD_Symbol_241
      REAL(w2f__8) OpenAD_Symbol_242
      type(active) :: OpenAD_Symbol_243
      REAL(w2f__8) OpenAD_Symbol_244
      REAL(w2f__8) OpenAD_Symbol_245
      REAL(w2f__8) OpenAD_Symbol_246
      type(active) :: OpenAD_Symbol_247
      REAL(w2f__8) OpenAD_Symbol_248
      REAL(w2f__8) OpenAD_Symbol_249
      REAL(w2f__8) OpenAD_Symbol_250
      REAL(w2f__8) OpenAD_Symbol_251
      REAL(w2f__8) OpenAD_Symbol_252
      type(active) :: OpenAD_Symbol_253
      REAL(w2f__8) OpenAD_Symbol_254
      REAL(w2f__8) OpenAD_Symbol_255
      REAL(w2f__8) OpenAD_Symbol_256
      REAL(w2f__8) OpenAD_Symbol_257
      REAL(w2f__8) OpenAD_Symbol_258
      REAL(w2f__8) OpenAD_Symbol_259
      REAL(w2f__8) OpenAD_Symbol_26
      REAL(w2f__8) OpenAD_Symbol_260
      REAL(w2f__8) OpenAD_Symbol_261
      REAL(w2f__8) OpenAD_Symbol_262
      REAL(w2f__8) OpenAD_Symbol_263
      type(active) :: OpenAD_Symbol_264
      REAL(w2f__8) OpenAD_Symbol_265
      REAL(w2f__8) OpenAD_Symbol_266
      REAL(w2f__8) OpenAD_Symbol_267
      REAL(w2f__8) OpenAD_Symbol_268
      REAL(w2f__8) OpenAD_Symbol_269
      REAL(w2f__8) OpenAD_Symbol_27
      REAL(w2f__8) OpenAD_Symbol_270
      REAL(w2f__8) OpenAD_Symbol_271
      REAL(w2f__8) OpenAD_Symbol_272
      REAL(w2f__8) OpenAD_Symbol_273
      REAL(w2f__8) OpenAD_Symbol_274
      REAL(w2f__8) OpenAD_Symbol_275
      REAL(w2f__8) OpenAD_Symbol_276
      REAL(w2f__8) OpenAD_Symbol_277
      REAL(w2f__8) OpenAD_Symbol_278
      REAL(w2f__8) OpenAD_Symbol_279
      REAL(w2f__8) OpenAD_Symbol_28
      REAL(w2f__8) OpenAD_Symbol_280
      REAL(w2f__8) OpenAD_Symbol_281
      REAL(w2f__8) OpenAD_Symbol_282
      REAL(w2f__8) OpenAD_Symbol_283
      type(active) :: OpenAD_Symbol_284
      type(active) :: OpenAD_Symbol_285
      type(active) :: OpenAD_Symbol_286
      type(active) :: OpenAD_Symbol_287
      type(active) :: OpenAD_Symbol_288
      type(active) :: OpenAD_Symbol_289
      REAL(w2f__8) OpenAD_Symbol_29
      type(active) :: OpenAD_Symbol_290
      type(active) :: OpenAD_Symbol_291
      type(active) :: OpenAD_Symbol_292
      type(active) :: OpenAD_Symbol_293
      type(active) :: OpenAD_Symbol_294
      type(active) :: OpenAD_Symbol_295
      type(active) :: OpenAD_Symbol_296
      type(active) :: OpenAD_Symbol_297
      type(active) :: OpenAD_Symbol_298
      type(active) :: OpenAD_Symbol_299
      REAL(w2f__8) OpenAD_Symbol_30
      INTEGER(w2f__i8) OpenAD_Symbol_300
      INTEGER(w2f__i8) OpenAD_Symbol_301
      INTEGER(w2f__i8) OpenAD_Symbol_302
      INTEGER(w2f__i8) OpenAD_Symbol_303
      INTEGER(w2f__i8) OpenAD_Symbol_304
      INTEGER(w2f__i8) OpenAD_Symbol_305
      INTEGER(w2f__i8) OpenAD_Symbol_306
      INTEGER(w2f__i8) OpenAD_Symbol_307
      INTEGER(w2f__i8) OpenAD_Symbol_308
      INTEGER(w2f__i8) OpenAD_Symbol_309
      INTEGER(w2f__i8) OpenAD_Symbol_310
      INTEGER(w2f__i8) OpenAD_Symbol_311
      INTEGER(w2f__i8) OpenAD_Symbol_312
      INTEGER(w2f__i8) OpenAD_Symbol_313
      INTEGER(w2f__i8) OpenAD_Symbol_314
      INTEGER(w2f__i8) OpenAD_Symbol_315
      INTEGER(w2f__i8) OpenAD_Symbol_316
      INTEGER(w2f__i8) OpenAD_Symbol_317
      INTEGER(w2f__i8) OpenAD_Symbol_318
      INTEGER(w2f__i8) OpenAD_Symbol_319
      REAL(w2f__8) OpenAD_Symbol_32
      INTEGER(w2f__i8) OpenAD_Symbol_320
      INTEGER(w2f__i8) OpenAD_Symbol_321
      INTEGER(w2f__i8) OpenAD_Symbol_322
      INTEGER(w2f__i8) OpenAD_Symbol_323
      INTEGER(w2f__i8) OpenAD_Symbol_324
      INTEGER(w2f__i8) OpenAD_Symbol_325
      INTEGER(w2f__i8) OpenAD_Symbol_326
      INTEGER(w2f__i8) OpenAD_Symbol_327
      INTEGER(w2f__i8) OpenAD_Symbol_328
      INTEGER(w2f__i8) OpenAD_Symbol_329
      REAL(w2f__8) OpenAD_Symbol_33
      INTEGER(w2f__i8) OpenAD_Symbol_330
      INTEGER(w2f__i8) OpenAD_Symbol_331
      INTEGER(w2f__i8) OpenAD_Symbol_332
      INTEGER(w2f__i8) OpenAD_Symbol_333
      INTEGER(w2f__i8) OpenAD_Symbol_334
      INTEGER(w2f__i8) OpenAD_Symbol_335
      INTEGER(w2f__i8) OpenAD_Symbol_336
      INTEGER(w2f__i8) OpenAD_Symbol_337
      INTEGER(w2f__i8) OpenAD_Symbol_338
      INTEGER(w2f__i8) OpenAD_Symbol_339
      REAL(w2f__8) OpenAD_Symbol_34
      INTEGER(w2f__i8) OpenAD_Symbol_340
      INTEGER(w2f__i8) OpenAD_Symbol_341
      INTEGER(w2f__i8) OpenAD_Symbol_342
      INTEGER(w2f__i8) OpenAD_Symbol_343
      INTEGER(w2f__i8) OpenAD_Symbol_344
      INTEGER(w2f__i8) OpenAD_Symbol_345
      INTEGER(w2f__i8) OpenAD_Symbol_346
      INTEGER(w2f__i8) OpenAD_Symbol_347
      INTEGER(w2f__i8) OpenAD_Symbol_348
      INTEGER(w2f__i8) OpenAD_Symbol_349
      REAL(w2f__8) OpenAD_Symbol_35
      INTEGER(w2f__i8) OpenAD_Symbol_350
      INTEGER(w2f__i8) OpenAD_Symbol_351
      INTEGER(w2f__i8) OpenAD_Symbol_352
      INTEGER(w2f__i8) OpenAD_Symbol_353
      INTEGER(w2f__i8) OpenAD_Symbol_354
      INTEGER(w2f__i8) OpenAD_Symbol_355
      INTEGER(w2f__i8) OpenAD_Symbol_356
      INTEGER(w2f__i8) OpenAD_Symbol_357
      INTEGER(w2f__i8) OpenAD_Symbol_358
      INTEGER(w2f__i8) OpenAD_Symbol_359
      REAL(w2f__8) OpenAD_Symbol_36
      INTEGER(w2f__i8) OpenAD_Symbol_360
      INTEGER(w2f__i8) OpenAD_Symbol_361
      INTEGER(w2f__i8) OpenAD_Symbol_362
      INTEGER(w2f__i8) OpenAD_Symbol_363
      INTEGER(w2f__i8) OpenAD_Symbol_364
      INTEGER(w2f__i8) OpenAD_Symbol_365
      INTEGER(w2f__i8) OpenAD_Symbol_366
      INTEGER(w2f__i8) OpenAD_Symbol_367
      INTEGER(w2f__i8) OpenAD_Symbol_368
      INTEGER(w2f__i8) OpenAD_Symbol_369
      INTEGER(w2f__i8) OpenAD_Symbol_370
      INTEGER(w2f__i8) OpenAD_Symbol_371
      INTEGER(w2f__i8) OpenAD_Symbol_372
      INTEGER(w2f__i8) OpenAD_Symbol_373
      INTEGER(w2f__i8) OpenAD_Symbol_374
      INTEGER(w2f__i8) OpenAD_Symbol_375
      INTEGER(w2f__i8) OpenAD_Symbol_376
      INTEGER(w2f__i8) OpenAD_Symbol_377
      INTEGER(w2f__i8) OpenAD_Symbol_378
      INTEGER(w2f__i8) OpenAD_Symbol_379
      REAL(w2f__8) OpenAD_Symbol_38
      INTEGER(w2f__i8) OpenAD_Symbol_380
      INTEGER(w2f__i8) OpenAD_Symbol_381
      INTEGER(w2f__i8) OpenAD_Symbol_382
      INTEGER(w2f__i8) OpenAD_Symbol_383
      REAL(w2f__8) OpenAD_Symbol_39
      REAL(w2f__8) OpenAD_Symbol_4
      REAL(w2f__8) OpenAD_Symbol_40
      REAL(w2f__8) OpenAD_Symbol_41
      REAL(w2f__8) OpenAD_Symbol_42
      REAL(w2f__8) OpenAD_Symbol_44
      REAL(w2f__8) OpenAD_Symbol_45
      REAL(w2f__8) OpenAD_Symbol_47
      REAL(w2f__8) OpenAD_Symbol_48
      REAL(w2f__8) OpenAD_Symbol_49
      REAL(w2f__8) OpenAD_Symbol_5
      REAL(w2f__8) OpenAD_Symbol_50
      REAL(w2f__8) OpenAD_Symbol_51
      REAL(w2f__8) OpenAD_Symbol_53
      REAL(w2f__8) OpenAD_Symbol_54
      REAL(w2f__8) OpenAD_Symbol_55
      REAL(w2f__8) OpenAD_Symbol_56
      REAL(w2f__8) OpenAD_Symbol_57
      REAL(w2f__8) OpenAD_Symbol_59
      REAL(w2f__8) OpenAD_Symbol_6
      REAL(w2f__8) OpenAD_Symbol_60
      REAL(w2f__8) OpenAD_Symbol_61
      REAL(w2f__8) OpenAD_Symbol_62
      REAL(w2f__8) OpenAD_Symbol_63
      REAL(w2f__8) OpenAD_Symbol_65
      REAL(w2f__8) OpenAD_Symbol_66
      REAL(w2f__8) OpenAD_Symbol_68
      REAL(w2f__8) OpenAD_Symbol_69
      REAL(w2f__8) OpenAD_Symbol_7
      REAL(w2f__8) OpenAD_Symbol_70
      REAL(w2f__8) OpenAD_Symbol_71
      REAL(w2f__8) OpenAD_Symbol_72
      REAL(w2f__8) OpenAD_Symbol_74
      REAL(w2f__8) OpenAD_Symbol_75
      REAL(w2f__8) OpenAD_Symbol_76
      REAL(w2f__8) OpenAD_Symbol_77
      REAL(w2f__8) OpenAD_Symbol_78
      REAL(w2f__8) OpenAD_Symbol_8
      REAL(w2f__8) OpenAD_Symbol_80
      REAL(w2f__8) OpenAD_Symbol_81
      REAL(w2f__8) OpenAD_Symbol_82
      REAL(w2f__8) OpenAD_Symbol_83
      REAL(w2f__8) OpenAD_Symbol_84
      REAL(w2f__8) OpenAD_Symbol_86
      REAL(w2f__8) OpenAD_Symbol_87
      REAL(w2f__8) OpenAD_Symbol_89
      REAL(w2f__8) OpenAD_Symbol_90
      REAL(w2f__8) OpenAD_Symbol_91
      REAL(w2f__8) OpenAD_Symbol_92
      REAL(w2f__8) OpenAD_Symbol_93
      REAL(w2f__8) OpenAD_Symbol_95
      REAL(w2f__8) OpenAD_Symbol_96
      REAL(w2f__8) OpenAD_Symbol_97
      REAL(w2f__8) OpenAD_Symbol_98
      REAL(w2f__8) OpenAD_Symbol_99
C
C     **** Parameters and Result ****
C
      INTEGER(w2f__i4) NX
      INTEGER(w2f__i4) NY
      type(active) :: X(1 : INT((NX * NY)))
      type(active) :: FVEC(1 : INT((NX * NY)))
      REAL(w2f__8) R
C
C     **** Local Variables and Functions ****
C
      INTEGER(w2f__i8) t__1
      INTEGER(w2f__i8) t__2
      type(active) :: DPDX
      type(active) :: DPDY
      REAL(w2f__8) FOUR
      PARAMETER ( FOUR = 4.0D00)
      REAL(w2f__8) HX
      REAL(w2f__8) HX2
      REAL(w2f__8) HY
      REAL(w2f__8) HY2
      INTEGER(w2f__i4) I
      INTEGER(w2f__i4) J
      INTEGER(w2f__i4) K
      INTEGER(w2f__i4) N
      REAL(w2f__8) NXP1
      REAL(w2f__8) NYP1
      REAL(w2f__8) ONE
      PARAMETER ( ONE = 1.0D00)
      type(active) :: P
      type(active) :: PB
      type(active) :: PBB
      type(active) :: PBL
      type(active) :: PBLAP
      type(active) :: PBR
      type(active) :: PL
      type(active) :: PLAP
      type(active) :: PLL
      type(active) :: PLLAP
      type(active) :: PR
      type(active) :: PRLAP
      type(active) :: PRR
      type(active) :: PT
      type(active) :: PTL
      type(active) :: PTLAP
      type(active) :: PTR
      type(active) :: PTT
      REAL(w2f__8) THREE
      PARAMETER ( THREE = 3.0D00)
      REAL(w2f__8) TWO
      PARAMETER ( TWO = 2.0D00)
      REAL(w2f__8) ZERO
      PARAMETER ( ZERO = 0.0D00)
      INTEGER(w2f__i4) t__3
      INTEGER(w2f__i4) t__4
      INTEGER(w2f__i8) OpenAD_Symbol_384
      INTEGER(w2f__i8) OpenAD_Symbol_385
      INTEGER(w2f__i8) OpenAD_Symbol_386
      INTEGER(w2f__i8) OpenAD_Symbol_387
      INTEGER(w2f__i8) OpenAD_Symbol_388
      INTEGER(w2f__i8) OpenAD_Symbol_389
      INTEGER(w2f__i8) OpenAD_Symbol_390
      INTEGER(w2f__i8) OpenAD_Symbol_391
      INTEGER(w2f__i8) OpenAD_Symbol_392
      INTEGER(w2f__i8) OpenAD_Symbol_393
      INTEGER(w2f__i8) OpenAD_Symbol_394
      INTEGER(w2f__i8) OpenAD_Symbol_395
      INTEGER(w2f__i8) OpenAD_Symbol_396
      INTEGER(w2f__i8) OpenAD_Symbol_397
      INTEGER(w2f__i8) OpenAD_Symbol_398
      INTEGER(w2f__i8) OpenAD_Symbol_399
      INTEGER(w2f__i8) OpenAD_Symbol_400
      INTEGER(w2f__i8) OpenAD_Symbol_401
      INTEGER(w2f__i8) OpenAD_Symbol_402
      INTEGER(w2f__i8) OpenAD_Symbol_403
      INTEGER(w2f__i8) OpenAD_Symbol_404
      INTEGER(w2f__i8) OpenAD_Symbol_405
      REAL(w2f__8) OpenAD_Symbol_406
      INTEGER(w2f__i8) OpenAD_Symbol_407
      REAL(w2f__8) OpenAD_Symbol_408
      INTEGER(w2f__i8) OpenAD_Symbol_409
      REAL(w2f__8) OpenAD_Symbol_410
      INTEGER(w2f__i8) OpenAD_Symbol_411
      REAL(w2f__8) OpenAD_Symbol_412
      INTEGER(w2f__i8) OpenAD_Symbol_413
      REAL(w2f__8) OpenAD_Symbol_414
      INTEGER(w2f__i8) OpenAD_Symbol_415
      REAL(w2f__8) OpenAD_Symbol_416
      INTEGER(w2f__i8) OpenAD_Symbol_417
      REAL(w2f__8) OpenAD_Symbol_418
      INTEGER(w2f__i8) OpenAD_Symbol_419
      REAL(w2f__8) OpenAD_Symbol_420
      INTEGER(w2f__i8) OpenAD_Symbol_421
      REAL(w2f__8) OpenAD_Symbol_422
      INTEGER(w2f__i8) OpenAD_Symbol_423
      REAL(w2f__8) OpenAD_Symbol_424
      INTEGER(w2f__i8) OpenAD_Symbol_425
      REAL(w2f__8) OpenAD_Symbol_426
      INTEGER(w2f__i8) OpenAD_Symbol_427
      REAL(w2f__8) OpenAD_Symbol_428
      INTEGER(w2f__i8) OpenAD_Symbol_429
      REAL(w2f__8) OpenAD_Symbol_430
      INTEGER(w2f__i8) OpenAD_Symbol_431
      REAL(w2f__8) OpenAD_Symbol_432
      INTEGER(w2f__i8) OpenAD_Symbol_433
      REAL(w2f__8) OpenAD_Symbol_434
      INTEGER(w2f__i8) OpenAD_Symbol_435
      REAL(w2f__8) OpenAD_Symbol_436
      INTEGER(w2f__i8) OpenAD_Symbol_437
      REAL(w2f__8) OpenAD_Symbol_438
      INTEGER(w2f__i8) OpenAD_Symbol_439
      REAL(w2f__8) OpenAD_Symbol_440
      INTEGER(w2f__i8) OpenAD_Symbol_441
      REAL(w2f__8) OpenAD_Symbol_442
      INTEGER(w2f__i8) OpenAD_Symbol_443
      REAL(w2f__8) OpenAD_Symbol_444
      INTEGER(w2f__i8) OpenAD_Symbol_445
      REAL(w2f__8) OpenAD_Symbol_446
      INTEGER(w2f__i8) OpenAD_Symbol_447
      REAL(w2f__8) OpenAD_Symbol_448
      INTEGER(w2f__i8) OpenAD_Symbol_449
      REAL(w2f__8) OpenAD_Symbol_450
      INTEGER(w2f__i8) OpenAD_Symbol_451
      REAL(w2f__8) OpenAD_Symbol_452
      INTEGER(w2f__i8) OpenAD_Symbol_453
      REAL(w2f__8) OpenAD_Symbol_454
      INTEGER(w2f__i8) OpenAD_Symbol_455
      REAL(w2f__8) OpenAD_Symbol_456
      INTEGER(w2f__i8) OpenAD_Symbol_457
      REAL(w2f__8) OpenAD_Symbol_458
      INTEGER(w2f__i8) OpenAD_Symbol_459
      REAL(w2f__8) OpenAD_Symbol_460
      INTEGER(w2f__i8) OpenAD_Symbol_461
      REAL(w2f__8) OpenAD_Symbol_462
      INTEGER(w2f__i8) OpenAD_Symbol_463
      REAL(w2f__8) OpenAD_Symbol_464
      INTEGER(w2f__i8) OpenAD_Symbol_465
      REAL(w2f__8) OpenAD_Symbol_466
      INTEGER(w2f__i8) OpenAD_Symbol_467
      REAL(w2f__8) OpenAD_Symbol_468
      INTEGER(w2f__i8) OpenAD_Symbol_469
      REAL(w2f__8) OpenAD_Symbol_470
      INTEGER(w2f__i8) OpenAD_Symbol_471
      REAL(w2f__8) OpenAD_Symbol_472
      INTEGER(w2f__i8) OpenAD_Symbol_473
      INTEGER(w2f__i8) OpenAD_Symbol_474
      INTEGER(w2f__i8) OpenAD_Symbol_475
      INTEGER(w2f__i8) OpenAD_Symbol_476
      INTEGER(w2f__i8) OpenAD_Symbol_477
      INTEGER(w2f__i8) OpenAD_Symbol_478
      INTEGER(w2f__i8) OpenAD_Symbol_479
      INTEGER(w2f__i8) OpenAD_Symbol_480
      INTEGER(w2f__i8) OpenAD_Symbol_481
      INTEGER(w2f__i8) OpenAD_Symbol_482
      INTEGER(w2f__i8) OpenAD_Symbol_483
      INTEGER(w2f__i8) OpenAD_Symbol_484
      INTEGER(w2f__i8) OpenAD_Symbol_485
      INTEGER(w2f__i8) OpenAD_Symbol_486
      INTEGER(w2f__i8) OpenAD_Symbol_487
      INTEGER(w2f__i8) OpenAD_Symbol_488
C
C     **** Top Level Pragmas ****
C
C$OPENAD INDEPENDENT(X)
C$OPENAD DEPENDENT(FVEC)
C
C     **** Statements ****
C


          ! checkpointing stacks and offsets
          integer :: cp_loop_variable_1,cp_loop_variable_2,
     +cp_loop_variable_3,cp_loop_variable_4,cp_loop_variable_5
          ! floats 'F'
          double precision, dimension(:), allocatable, save :: 
     +theArgFStack
          integer, save :: theArgFStackoffset=0, theArgFStackSize=0
          ! integers 'I'
          integer, dimension(:), allocatable, save :: 
     +theArgIStack
          integer, save :: theArgIStackoffset=0, theArgIStackSize=0
          ! booleans 'B'
          logical, dimension(:), allocatable, save :: 
     +theArgBStack
          integer, save :: theArgBStackoffset=0, theArgBStackSize=0
          ! strings 'S'
          character*(80), dimension(:), allocatable, save :: 
     +theArgSStack
          integer, save :: theArgSStackoffset=0, theArgSStackSize=0

          type(modeType) :: our_orig_mode

	  ! call external C function used in inlined code
          integer iaddr
          external iaddr

C          write(*,'(A,I6,A,I6,A,I5,A,I5)')
C     +"b:AF:", theArgFStackoffset, 
C     +" AI:",theArgIStackoffset, 
C     +" DT:",double_tape_pointer, 
C     +" IT:",integer_tape_pointer
          if (our_rev_mode%arg_store) then 
C            print*, " arg_store  ", our_rev_mode
C store arguments
          end if 
          if (our_rev_mode%arg_restore) then
C            print*, " arg_restore", our_rev_mode
C restore arguments
          end if
          if (our_rev_mode%plain) then
C            print*, " plain      ", our_rev_mode
            our_orig_mode=our_rev_mode
            our_rev_mode%arg_store=.FALSE.
C original function
C$OPENAD XXX Template ad_template.f
      t__1 = INT(NX * NY)
      t__2 = MAX(INT(NX * NY), 0_w2f__i8)
      N = NX * NY
      NXP1 = (NX + INT(1_w2f__i8))
      NYP1 = (NY + INT(1_w2f__i8))
      HX = (1.0D00 / NXP1)
      HY = (1.0D00 / NYP1)
      HY2 = (HY * HY)
      HX2 = (HX * HX)
      t__3 = NY
      DO I = 1, NY, 1
        t__4 = NX
        DO J = 1, NX, 1
          K = J + NX *(I +(-1))
          IF((I .eq. INT(1_w2f__i8)) .OR.(J .eq. INT(1_w2f__i8))) THEN
            PBL%v = 0.0D00
          ELSE
            PBL%v = X(K-NX+(-1))%v
          ENDIF
          IF(I .eq. INT(1_w2f__i8)) THEN
            PB%v = 0.0D00
            PBB%v = X(K)%v
          ELSE
            IF(I .eq. INT(2_w2f__i8)) THEN
              PB%v = X(K-NX)%v
              PBB%v = 0.0D00
            ELSE
              PB%v = X(K-NX)%v
              PBB%v = X(K-NX*2)%v
            ENDIF
          ENDIF
          IF((NX .eq. J) .OR.(I .eq. INT(1_w2f__i8))) THEN
            PBR%v = 0.0D00
          ELSE
            PBR%v = X(K-NX+1)%v
          ENDIF
          IF(J .eq. INT(1_w2f__i8)) THEN
            PL%v = 0.0D00
            PLL%v = X(K)%v
          ELSE
            IF(J .eq. INT(2_w2f__i8)) THEN
              PL%v = X(K+(-1))%v
              PLL%v = 0.0D00
            ELSE
              PL%v = X(K+(-1))%v
              PLL%v = X(K+(-2))%v
            ENDIF
          ENDIF
          P%v = X(K)%v
          IF(J .eq.(NX + INT((-1_w2f__i8)))) THEN
            PR%v = X(K+1)%v
            PRR%v = 0.0D00
          ELSE
            IF(NX .eq. J) THEN
              PR%v = 0.0D00
              PRR%v = X(K)%v
            ELSE
              PR%v = X(K+1)%v
              PRR%v = X(K+2)%v
            ENDIF
          ENDIF
          IF((NY .eq. I) .OR.(J .eq. INT(1_w2f__i8))) THEN
            PTL%v = 0.0D00
          ELSE
            PTL%v = X(NX+K+(-1))%v
          ENDIF
          IF(I .eq.(NY + INT((-1_w2f__i8)))) THEN
            PT%v = X(NX+K)%v
            PTT%v = 0.0D00
          ELSE
            IF(NY .eq. I) THEN
              PT%v = 0.0D00
              PTT%v = X(K)%v
            ELSE
              PT%v = X(NX+K)%v
              PTT%v = X(K+NX*2)%v
            ENDIF
          ENDIF
          IF((NX .eq. J) .OR.(NY .eq. I)) THEN
            PTR%v = 0.0D00
          ELSE
            PTR%v = X(NX+K+1)%v
          ENDIF
          DPDY%v = ((PT%v-PB%v)/(HY*2.0D00))
          DPDX%v = ((PR%v-PL%v)/(HX*2.0D00))
          PBLAP%v = (((PBB%v+P%v-PB%v*2.0D00)/HY2)+((PBL%v+PBR%v-PB%v*2.
     +0D00)/HX2))
          PLLAP%v = (((PBL%v+PTL%v-PL%v*2.0D00)/HY2)+((PLL%v+P%v-PL%v*2.
     +0D00)/HX2))
          PLAP%v = (((PB%v+PT%v-P%v*2.0D00)/HY2)+((PL%v+PR%v-P%v*2.0D00)
     +/HX2))
          PRLAP%v = (((P%v+PRR%v-PR%v*2.0D00)/HX2)+((PBR%v+PTR%v-PR%v*2.
     +0D00)/HY2))
          PTLAP%v = (((P%v+PTT%v-PT%v*2.0D00)/HY2)+((PTL%v+PTR%v-PT%v*2.
     +0D00)/HX2))
          FVEC(INT(K))%v = (((PBLAP%v+PTLAP%v-PLAP%v*2.0D00)/HY2)+((PLLA
     +P%v+PRLAP%v-PLAP%v*2.0D00)/HX2)-R*(((DPDY%v*(PRLAP%v-PLLAP%v))/(HX
     +*2.0D00))-((DPDX%v*(PTLAP%v-PBLAP%v))/(HY*2.0D00))))
        END DO
      END DO
      RETURN
            our_rev_mode=our_orig_mode
          end if 
          if (our_rev_mode%tape) then
C            print*, " tape       ", our_rev_mode
            our_rev_mode%arg_store=.TRUE.
            our_rev_mode%arg_restore=.FALSE.
            our_rev_mode%res_store=.FALSE.
            our_rev_mode%res_restore=.FALSE.
            our_rev_mode%plain=.TRUE.
            our_rev_mode%tape=.FALSE.
            our_rev_mode%adjoint=.FALSE.
C taping
C$OPENAD XXX Template ad_template.f
      t__1 = INT(NX * NY)
      t__2 = MAX(INT(NX * NY), 0_w2f__i8)
      N = NX * NY
      NXP1 = (NX + INT(1_w2f__i8))
      NYP1 = (NY + INT(1_w2f__i8))
      HX = (1.0D00 / NXP1)
      HY = (1.0D00 / NYP1)
      HY2 = (HY * HY)
      HX2 = (HX * HX)
      t__3 = NY
      OpenAD_Symbol_316 = 0_w2f__i8
      DO I = 1, NY, 1
        t__4 = NX
        OpenAD_Symbol_317 = 0_w2f__i8
        DO J = 1, NX, 1
          K = J + NX *(I +(-1))
          IF((I .eq. INT(1_w2f__i8)) .OR.(J .eq. INT(1_w2f__i8))) THEN
            PBL%v = 0.0D00
            OpenAD_Symbol_318 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_318
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            PBL%v = X(K-NX+(-1))%v
            OpenAD_Symbol_399 = (K - NX + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_399
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_319 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_319
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          IF(I .eq. INT(1_w2f__i8)) THEN
            PB%v = 0.0D00
            PBB%v = X(K)%v
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_322 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_322
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            IF(I .eq. INT(2_w2f__i8)) THEN
              PB%v = X(K-NX)%v
              PBB%v = 0.0D00
              OpenAD_Symbol_396 = (K - NX)
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_396
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_320 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_320
          integer_tape_pointer = integer_tape_pointer+1
            ELSE
              PB%v = X(K-NX)%v
              PBB%v = X(K-NX*2)%v
              OpenAD_Symbol_397 = (K - NX * INT(2_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_397
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_398 = (K - NX)
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_398
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_321 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_321
          integer_tape_pointer = integer_tape_pointer+1
            ENDIF
            OpenAD_Symbol_323 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_323
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          IF((NX .eq. J) .OR.(I .eq. INT(1_w2f__i8))) THEN
            PBR%v = 0.0D00
            OpenAD_Symbol_324 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_324
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            PBR%v = X(K-NX+1)%v
            OpenAD_Symbol_395 = (K - NX + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_395
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_325 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_325
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          IF(J .eq. INT(1_w2f__i8)) THEN
            PL%v = 0.0D00
            PLL%v = X(K)%v
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_328 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_328
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            IF(J .eq. INT(2_w2f__i8)) THEN
              PL%v = X(K+(-1))%v
              PLL%v = 0.0D00
              OpenAD_Symbol_392 = (K + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_392
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_326 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_326
          integer_tape_pointer = integer_tape_pointer+1
            ELSE
              PL%v = X(K+(-1))%v
              PLL%v = X(K+(-2))%v
              OpenAD_Symbol_393 = (K + INT((-2_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_393
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_394 = (K + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_394
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_327 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_327
          integer_tape_pointer = integer_tape_pointer+1
            ENDIF
            OpenAD_Symbol_329 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_329
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          P%v = X(K)%v
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          IF(J .eq.(NX + INT((-1_w2f__i8)))) THEN
            PR%v = X(K+1)%v
            PRR%v = 0.0D00
            OpenAD_Symbol_384 = (K + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_384
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_332 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_332
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            IF(NX .eq. J) THEN
              PR%v = 0.0D00
              PRR%v = X(K)%v
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_330 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_330
          integer_tape_pointer = integer_tape_pointer+1
            ELSE
              PR%v = X(K+1)%v
              PRR%v = X(K+2)%v
              OpenAD_Symbol_390 = (K + INT(2_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_390
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_391 = (K + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_391
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_331 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_331
          integer_tape_pointer = integer_tape_pointer+1
            ENDIF
            OpenAD_Symbol_333 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_333
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          IF((NY .eq. I) .OR.(J .eq. INT(1_w2f__i8))) THEN
            PTL%v = 0.0D00
            OpenAD_Symbol_334 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_334
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            PTL%v = X(NX+K+(-1))%v
            OpenAD_Symbol_389 = (NX + K + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_389
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_335 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_335
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          IF(I .eq.(NY + INT((-1_w2f__i8)))) THEN
            PT%v = X(NX+K)%v
            PTT%v = 0.0D00
            OpenAD_Symbol_385 = (NX + K)
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_385
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_338 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_338
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            IF(NY .eq. I) THEN
              PT%v = 0.0D00
              PTT%v = X(K)%v
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_336 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_336
          integer_tape_pointer = integer_tape_pointer+1
            ELSE
              PT%v = X(NX+K)%v
              PTT%v = X(K+NX*2)%v
              OpenAD_Symbol_387 = (K + NX * INT(2_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_387
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_388 = (NX + K)
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_388
          integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_337 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_337
          integer_tape_pointer = integer_tape_pointer+1
            ENDIF
            OpenAD_Symbol_339 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_339
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          IF((NX .eq. J) .OR.(NY .eq. I)) THEN
            PTR%v = 0.0D00
            OpenAD_Symbol_340 = 1_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_340
          integer_tape_pointer = integer_tape_pointer+1
          ELSE
            PTR%v = X(NX+K+1)%v
            OpenAD_Symbol_386 = (NX + K + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_386
          integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_341 = 0_w2f__i8
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_341
          integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          OpenAD_Symbol_0 = (PT%v-PB%v)
          OpenAD_Symbol_1 = (HY * 2.0D00)
          DPDY%v = (OpenAD_Symbol_0/OpenAD_Symbol_1)
          OpenAD_Symbol_4 = 1_w2f__i8
          OpenAD_Symbol_5 = (-1_w2f__i8)
          OpenAD_Symbol_2 = (INT(1_w2f__i8) / OpenAD_Symbol_1)
          OpenAD_Symbol_6 = (PR%v-PL%v)
          OpenAD_Symbol_7 = (HX * 2.0D00)
          DPDX%v = (OpenAD_Symbol_6/OpenAD_Symbol_7)
          OpenAD_Symbol_10 = 1_w2f__i8
          OpenAD_Symbol_11 = (-1_w2f__i8)
          OpenAD_Symbol_8 = (INT(1_w2f__i8) / OpenAD_Symbol_7)
          OpenAD_Symbol_14 = (PBB%v+P%v-PB%v*2.0D00)
          OpenAD_Symbol_23 = (PBL%v+PBR%v-PB%v*2.0D00)
          OpenAD_Symbol_32 = ((OpenAD_Symbol_14 / HY2) +( OpenAD_Symbol_
     +23 / HX2))
          OpenAD_Symbol_17 = 1_w2f__i8
          OpenAD_Symbol_19 = 1_w2f__i8
          OpenAD_Symbol_21 = 2.0D00
          OpenAD_Symbol_20 = (-1_w2f__i8)
          OpenAD_Symbol_18 = 1_w2f__i8
          OpenAD_Symbol_15 = (INT(1_w2f__i8) / HY2)
          OpenAD_Symbol_12 = 1_w2f__i8
          OpenAD_Symbol_26 = 1_w2f__i8
          OpenAD_Symbol_28 = 1_w2f__i8
          OpenAD_Symbol_30 = 2.0D00
          OpenAD_Symbol_29 = (-1_w2f__i8)
          OpenAD_Symbol_27 = 1_w2f__i8
          OpenAD_Symbol_24 = (INT(1_w2f__i8) / HX2)
          OpenAD_Symbol_13 = 1_w2f__i8
          PBLAP%v = OpenAD_Symbol_32
          OpenAD_Symbol_35 = (PBL%v+PTL%v-PL%v*2.0D00)
          OpenAD_Symbol_44 = (PLL%v+P%v-PL%v*2.0D00)
          OpenAD_Symbol_53 = ((OpenAD_Symbol_35 / HY2) +( OpenAD_Symbol_
     +44 / HX2))
          OpenAD_Symbol_38 = 1_w2f__i8
          OpenAD_Symbol_40 = 1_w2f__i8
          OpenAD_Symbol_42 = 2.0D00
          OpenAD_Symbol_41 = (-1_w2f__i8)
          OpenAD_Symbol_39 = 1_w2f__i8
          OpenAD_Symbol_36 = (INT(1_w2f__i8) / HY2)
          OpenAD_Symbol_33 = 1_w2f__i8
          OpenAD_Symbol_47 = 1_w2f__i8
          OpenAD_Symbol_49 = 1_w2f__i8
          OpenAD_Symbol_51 = 2.0D00
          OpenAD_Symbol_50 = (-1_w2f__i8)
          OpenAD_Symbol_48 = 1_w2f__i8
          OpenAD_Symbol_45 = (INT(1_w2f__i8) / HX2)
          OpenAD_Symbol_34 = 1_w2f__i8
          PLLAP%v = OpenAD_Symbol_53
          OpenAD_Symbol_56 = (PB%v+PT%v-P%v*2.0D00)
          OpenAD_Symbol_65 = (PL%v+PR%v-P%v*2.0D00)
          OpenAD_Symbol_74 = ((OpenAD_Symbol_56 / HY2) +( OpenAD_Symbol_
     +65 / HX2))
          OpenAD_Symbol_59 = 1_w2f__i8
          OpenAD_Symbol_61 = 1_w2f__i8
          OpenAD_Symbol_63 = 2.0D00
          OpenAD_Symbol_62 = (-1_w2f__i8)
          OpenAD_Symbol_60 = 1_w2f__i8
          OpenAD_Symbol_57 = (INT(1_w2f__i8) / HY2)
          OpenAD_Symbol_54 = 1_w2f__i8
          OpenAD_Symbol_68 = 1_w2f__i8
          OpenAD_Symbol_70 = 1_w2f__i8
          OpenAD_Symbol_72 = 2.0D00
          OpenAD_Symbol_71 = (-1_w2f__i8)
          OpenAD_Symbol_69 = 1_w2f__i8
          OpenAD_Symbol_66 = (INT(1_w2f__i8) / HX2)
          OpenAD_Symbol_55 = 1_w2f__i8
          PLAP%v = OpenAD_Symbol_74
          OpenAD_Symbol_77 = (P%v+PRR%v-PR%v*2.0D00)
          OpenAD_Symbol_86 = (PBR%v+PTR%v-PR%v*2.0D00)
          OpenAD_Symbol_95 = ((OpenAD_Symbol_77 / HX2) +( OpenAD_Symbol_
     +86 / HY2))
          OpenAD_Symbol_80 = 1_w2f__i8
          OpenAD_Symbol_82 = 1_w2f__i8
          OpenAD_Symbol_84 = 2.0D00
          OpenAD_Symbol_83 = (-1_w2f__i8)
          OpenAD_Symbol_81 = 1_w2f__i8
          OpenAD_Symbol_78 = (INT(1_w2f__i8) / HX2)
          OpenAD_Symbol_75 = 1_w2f__i8
          OpenAD_Symbol_89 = 1_w2f__i8
          OpenAD_Symbol_91 = 1_w2f__i8
          OpenAD_Symbol_93 = 2.0D00
          OpenAD_Symbol_92 = (-1_w2f__i8)
          OpenAD_Symbol_90 = 1_w2f__i8
          OpenAD_Symbol_87 = (INT(1_w2f__i8) / HY2)
          OpenAD_Symbol_76 = 1_w2f__i8
          PRLAP%v = OpenAD_Symbol_95
          OpenAD_Symbol_98 = (P%v+PTT%v-PT%v*2.0D00)
          OpenAD_Symbol_107 = (PTL%v+PTR%v-PT%v*2.0D00)
          OpenAD_Symbol_116 = ((OpenAD_Symbol_98 / HY2) +( OpenAD_Symbol
     +_107 / HX2))
          OpenAD_Symbol_101 = 1_w2f__i8
          OpenAD_Symbol_103 = 1_w2f__i8
          OpenAD_Symbol_105 = 2.0D00
          OpenAD_Symbol_104 = (-1_w2f__i8)
          OpenAD_Symbol_102 = 1_w2f__i8
          OpenAD_Symbol_99 = (INT(1_w2f__i8) / HY2)
          OpenAD_Symbol_96 = 1_w2f__i8
          OpenAD_Symbol_110 = 1_w2f__i8
          OpenAD_Symbol_112 = 1_w2f__i8
          OpenAD_Symbol_114 = 2.0D00
          OpenAD_Symbol_113 = (-1_w2f__i8)
          OpenAD_Symbol_111 = 1_w2f__i8
          OpenAD_Symbol_108 = (INT(1_w2f__i8) / HX2)
          OpenAD_Symbol_97 = 1_w2f__i8
          PTLAP%v = OpenAD_Symbol_116
          OpenAD_Symbol_121 = (PBLAP%v+PTLAP%v-PLAP%v*2.0D00)
          OpenAD_Symbol_130 = (PLLAP%v+PRLAP%v-PLAP%v*2.0D00)
          OpenAD_Symbol_148 = (PRLAP%v-PLLAP%v)
          OpenAD_Symbol_144 = (DPDY%v*OpenAD_Symbol_148)
          OpenAD_Symbol_145 = (HX * 2.0D00)
          OpenAD_Symbol_157 = (PTLAP%v-PBLAP%v)
          OpenAD_Symbol_153 = (DPDX%v*OpenAD_Symbol_157)
          OpenAD_Symbol_154 = (HY * 2.0D00)
          OpenAD_Symbol_139 = ((OpenAD_Symbol_144 / OpenAD_Symbol_145)  
     +-(OpenAD_Symbol_153 / OpenAD_Symbol_154))
          OpenAD_Symbol_162 = ((OpenAD_Symbol_121 / HY2) +( OpenAD_Symbo
     +l_130 / HX2) - R * OpenAD_Symbol_139)
          OpenAD_Symbol_124 = 1_w2f__i8
          OpenAD_Symbol_126 = 1_w2f__i8
          OpenAD_Symbol_128 = 2.0D00
          OpenAD_Symbol_127 = (-1_w2f__i8)
          OpenAD_Symbol_125 = 1_w2f__i8
          OpenAD_Symbol_122 = (INT(1_w2f__i8) / HY2)
          OpenAD_Symbol_119 = 1_w2f__i8
          OpenAD_Symbol_133 = 1_w2f__i8
          OpenAD_Symbol_135 = 1_w2f__i8
          OpenAD_Symbol_137 = 2.0D00
          OpenAD_Symbol_136 = (-1_w2f__i8)
          OpenAD_Symbol_134 = 1_w2f__i8
          OpenAD_Symbol_131 = (INT(1_w2f__i8) / HX2)
          OpenAD_Symbol_120 = 1_w2f__i8
          OpenAD_Symbol_117 = 1_w2f__i8
          OpenAD_Symbol_149 = OpenAD_Symbol_148
          OpenAD_Symbol_151 = 1_w2f__i8
          OpenAD_Symbol_152 = (-1_w2f__i8)
          OpenAD_Symbol_150 = DPDY%v
          OpenAD_Symbol_146 = (INT(1_w2f__i8) / OpenAD_Symbol_145)
          OpenAD_Symbol_142 = 1_w2f__i8
          OpenAD_Symbol_158 = OpenAD_Symbol_157
          OpenAD_Symbol_160 = 1_w2f__i8
          OpenAD_Symbol_161 = (-1_w2f__i8)
          OpenAD_Symbol_159 = DPDX%v
          OpenAD_Symbol_155 = (INT(1_w2f__i8) / OpenAD_Symbol_154)
          OpenAD_Symbol_143 = (-1_w2f__i8)
          OpenAD_Symbol_141 = R
          OpenAD_Symbol_118 = (-1_w2f__i8)
          FVEC(INT(K))%v = OpenAD_Symbol_162
          OpenAD_Symbol_168 = (OpenAD_Symbol_119 * OpenAD_Symbol_117)
          OpenAD_Symbol_169 = (OpenAD_Symbol_120 * OpenAD_Symbol_117)
          OpenAD_Symbol_170 = (OpenAD_Symbol_141 * OpenAD_Symbol_118)
          OpenAD_Symbol_171 = (OpenAD_Symbol_142 * OpenAD_Symbol_170)
          OpenAD_Symbol_172 = (OpenAD_Symbol_143 * OpenAD_Symbol_170)
          OpenAD_Symbol_173 = (OpenAD_Symbol_131 * OpenAD_Symbol_169)
          OpenAD_Symbol_174 = (OpenAD_Symbol_133 * OpenAD_Symbol_173)
          OpenAD_Symbol_175 = (OpenAD_Symbol_134 * OpenAD_Symbol_173)
          OpenAD_Symbol_176 = (OpenAD_Symbol_135 * OpenAD_Symbol_175)
          OpenAD_Symbol_177 = (OpenAD_Symbol_136 * OpenAD_Symbol_175)
          OpenAD_Symbol_178 = (OpenAD_Symbol_122 * OpenAD_Symbol_168)
          OpenAD_Symbol_179 = (OpenAD_Symbol_124 * OpenAD_Symbol_178)
          OpenAD_Symbol_180 = (OpenAD_Symbol_125 * OpenAD_Symbol_178)
          OpenAD_Symbol_181 = (OpenAD_Symbol_126 * OpenAD_Symbol_180)
          OpenAD_Symbol_182 = (OpenAD_Symbol_127 * OpenAD_Symbol_180)
          OpenAD_Symbol_183 = (OpenAD_Symbol_155 * OpenAD_Symbol_172)
          OpenAD_Symbol_184 = (OpenAD_Symbol_158 * OpenAD_Symbol_183)
          OpenAD_Symbol_185 = (OpenAD_Symbol_159 * OpenAD_Symbol_183)
          OpenAD_Symbol_186 = (OpenAD_Symbol_181 + OpenAD_Symbol_160 *  
     +OpenAD_Symbol_185)
          OpenAD_Symbol_187 = (OpenAD_Symbol_179 + OpenAD_Symbol_161 *  
     +OpenAD_Symbol_185)
          OpenAD_Symbol_188 = (OpenAD_Symbol_96 * OpenAD_Symbol_186)
          OpenAD_Symbol_189 = (OpenAD_Symbol_97 * OpenAD_Symbol_186)
          OpenAD_Symbol_190 = (OpenAD_Symbol_12 * OpenAD_Symbol_187)
          OpenAD_Symbol_191 = (OpenAD_Symbol_13 * OpenAD_Symbol_187)
          OpenAD_Symbol_192 = (OpenAD_Symbol_146 * OpenAD_Symbol_171)
          OpenAD_Symbol_193 = (OpenAD_Symbol_149 * OpenAD_Symbol_192)
          OpenAD_Symbol_194 = (OpenAD_Symbol_150 * OpenAD_Symbol_192)
          OpenAD_Symbol_195 = (OpenAD_Symbol_176 + OpenAD_Symbol_151 *  
     +OpenAD_Symbol_194)
          OpenAD_Symbol_196 = (OpenAD_Symbol_174 + OpenAD_Symbol_152 *  
     +OpenAD_Symbol_194)
          OpenAD_Symbol_197 = (OpenAD_Symbol_75 * OpenAD_Symbol_195)
          OpenAD_Symbol_198 = (OpenAD_Symbol_76 * OpenAD_Symbol_195)
          OpenAD_Symbol_199 = (OpenAD_Symbol_33 * OpenAD_Symbol_196)
          OpenAD_Symbol_200 = (OpenAD_Symbol_34 * OpenAD_Symbol_196)
          OpenAD_Symbol_201 = (OpenAD_Symbol_137 * OpenAD_Symbol_177)
          OpenAD_Symbol_202 = (OpenAD_Symbol_201 + OpenAD_Symbol_128 *  
     +OpenAD_Symbol_182)
          OpenAD_Symbol_203 = (OpenAD_Symbol_54 * OpenAD_Symbol_202)
          OpenAD_Symbol_204 = (OpenAD_Symbol_55 * OpenAD_Symbol_202)
          OpenAD_Symbol_205 = (OpenAD_Symbol_108 * OpenAD_Symbol_189)
          OpenAD_Symbol_206 = (OpenAD_Symbol_110 * OpenAD_Symbol_205)
          OpenAD_Symbol_208 = (OpenAD_Symbol_111 * OpenAD_Symbol_205)
          OpenAD_Symbol_209 = (OpenAD_Symbol_112 * OpenAD_Symbol_208)
          OpenAD_Symbol_211 = (OpenAD_Symbol_113 * OpenAD_Symbol_208)
          OpenAD_Symbol_212 = (OpenAD_Symbol_99 * OpenAD_Symbol_188)
          OpenAD_Symbol_213 = (OpenAD_Symbol_101 * OpenAD_Symbol_212)
          OpenAD_Symbol_215 = (OpenAD_Symbol_102 * OpenAD_Symbol_212)
          OpenAD_Symbol_216 = (OpenAD_Symbol_103 * OpenAD_Symbol_215)
          OpenAD_Symbol_218 = (OpenAD_Symbol_104 * OpenAD_Symbol_215)
          OpenAD_Symbol_219 = (OpenAD_Symbol_87 * OpenAD_Symbol_198)
          OpenAD_Symbol_220 = (OpenAD_Symbol_89 * OpenAD_Symbol_219)
          OpenAD_Symbol_222 = (OpenAD_Symbol_90 * OpenAD_Symbol_219)
          OpenAD_Symbol_223 = (OpenAD_Symbol_91 * OpenAD_Symbol_222)
          OpenAD_Symbol_224 = (OpenAD_Symbol_92 * OpenAD_Symbol_222)
          OpenAD_Symbol_225 = (OpenAD_Symbol_78 * OpenAD_Symbol_197)
          OpenAD_Symbol_226 = (OpenAD_Symbol_80 * OpenAD_Symbol_225)
          OpenAD_Symbol_227 = (OpenAD_Symbol_81 * OpenAD_Symbol_225)
          OpenAD_Symbol_228 = (OpenAD_Symbol_82 * OpenAD_Symbol_227)
          OpenAD_Symbol_230 = (OpenAD_Symbol_83 * OpenAD_Symbol_227)
          OpenAD_Symbol_231 = (OpenAD_Symbol_66 * OpenAD_Symbol_204)
          OpenAD_Symbol_232 = (OpenAD_Symbol_68 * OpenAD_Symbol_231)
          OpenAD_Symbol_234 = (OpenAD_Symbol_69 * OpenAD_Symbol_231)
          OpenAD_Symbol_235 = (OpenAD_Symbol_70 * OpenAD_Symbol_234)
          OpenAD_Symbol_237 = (OpenAD_Symbol_71 * OpenAD_Symbol_234)
          OpenAD_Symbol_238 = (OpenAD_Symbol_57 * OpenAD_Symbol_203)
          OpenAD_Symbol_239 = (OpenAD_Symbol_59 * OpenAD_Symbol_238)
          OpenAD_Symbol_241 = (OpenAD_Symbol_60 * OpenAD_Symbol_238)
          OpenAD_Symbol_242 = (OpenAD_Symbol_61 * OpenAD_Symbol_241)
          OpenAD_Symbol_244 = (OpenAD_Symbol_62 * OpenAD_Symbol_241)
          OpenAD_Symbol_245 = (OpenAD_Symbol_45 * OpenAD_Symbol_200)
          OpenAD_Symbol_246 = (OpenAD_Symbol_47 * OpenAD_Symbol_245)
          OpenAD_Symbol_248 = (OpenAD_Symbol_48 * OpenAD_Symbol_245)
          OpenAD_Symbol_249 = (OpenAD_Symbol_49 * OpenAD_Symbol_248)
          OpenAD_Symbol_250 = (OpenAD_Symbol_50 * OpenAD_Symbol_248)
          OpenAD_Symbol_251 = (OpenAD_Symbol_36 * OpenAD_Symbol_199)
          OpenAD_Symbol_252 = (OpenAD_Symbol_38 * OpenAD_Symbol_251)
          OpenAD_Symbol_254 = (OpenAD_Symbol_39 * OpenAD_Symbol_251)
          OpenAD_Symbol_255 = (OpenAD_Symbol_40 * OpenAD_Symbol_254)
          OpenAD_Symbol_256 = (OpenAD_Symbol_41 * OpenAD_Symbol_254)
          OpenAD_Symbol_257 = (OpenAD_Symbol_24 * OpenAD_Symbol_191)
          OpenAD_Symbol_258 = (OpenAD_Symbol_26 * OpenAD_Symbol_257)
          OpenAD_Symbol_259 = (OpenAD_Symbol_27 * OpenAD_Symbol_257)
          OpenAD_Symbol_260 = (OpenAD_Symbol_28 * OpenAD_Symbol_259)
          OpenAD_Symbol_261 = (OpenAD_Symbol_29 * OpenAD_Symbol_259)
          OpenAD_Symbol_262 = (OpenAD_Symbol_15 * OpenAD_Symbol_190)
          OpenAD_Symbol_263 = (OpenAD_Symbol_17 * OpenAD_Symbol_262)
          OpenAD_Symbol_265 = (OpenAD_Symbol_18 * OpenAD_Symbol_262)
          OpenAD_Symbol_266 = (OpenAD_Symbol_19 * OpenAD_Symbol_265)
          OpenAD_Symbol_267 = (OpenAD_Symbol_20 * OpenAD_Symbol_265)
          OpenAD_Symbol_268 = (OpenAD_Symbol_8 * OpenAD_Symbol_184)
          OpenAD_Symbol_269 = (OpenAD_Symbol_10 * OpenAD_Symbol_268)
          OpenAD_Symbol_270 = (OpenAD_Symbol_11 * OpenAD_Symbol_268)
          OpenAD_Symbol_271 = (OpenAD_Symbol_2 * OpenAD_Symbol_193)
          OpenAD_Symbol_272 = (OpenAD_Symbol_4 * OpenAD_Symbol_271)
          OpenAD_Symbol_273 = (OpenAD_Symbol_5 * OpenAD_Symbol_271)
          OpenAD_Symbol_274 = (OpenAD_Symbol_114 * OpenAD_Symbol_211)
          OpenAD_Symbol_275 = (OpenAD_Symbol_105 * OpenAD_Symbol_218)
          OpenAD_Symbol_276 = (OpenAD_Symbol_93 * OpenAD_Symbol_224)
          OpenAD_Symbol_277 = (OpenAD_Symbol_84 * OpenAD_Symbol_230)
          OpenAD_Symbol_278 = (OpenAD_Symbol_72 * OpenAD_Symbol_237)
          OpenAD_Symbol_279 = (OpenAD_Symbol_63 * OpenAD_Symbol_244)
          OpenAD_Symbol_280 = (OpenAD_Symbol_51 * OpenAD_Symbol_250)
          OpenAD_Symbol_281 = (OpenAD_Symbol_42 * OpenAD_Symbol_256)
          OpenAD_Symbol_282 = (OpenAD_Symbol_30 * OpenAD_Symbol_261)
          OpenAD_Symbol_283 = (OpenAD_Symbol_21 * OpenAD_Symbol_267)
          double_tape(double_tape_pointer) = OpenAD_Symbol_206
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_209
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_213
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_216
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_220
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_223
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_226
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_228
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_232
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_235
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_239
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_242
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_246
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_249
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_252
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_255
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_258
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_260
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_263
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_266
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_269
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_270
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_272
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_273
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_274
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_275
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_276
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_277
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_278
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_279
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_280
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_281
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_282
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_283
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          OpenAD_Symbol_317 = (INT(OpenAD_Symbol_317) + INT(1_w2f__i8))
        END DO
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_317
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_316 = (INT(OpenAD_Symbol_316) + INT(1_w2f__i8))
      END DO
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_316
          integer_tape_pointer = integer_tape_pointer+1
      RETURN
            our_rev_mode%arg_store=.FALSE.
            our_rev_mode%arg_restore=.FALSE.
            our_rev_mode%res_store=.FALSE.
            our_rev_mode%res_restore=.FALSE.
            our_rev_mode%plain=.FALSE.
            our_rev_mode%tape=.FALSE.
            our_rev_mode%adjoint=.TRUE.
          end if 
          if (our_rev_mode%adjoint) then
C            print*, " adjoint    ", our_rev_mode
            our_rev_mode%arg_store=.FALSE.
            our_rev_mode%arg_restore=.TRUE.
            our_rev_mode%res_store=.FALSE.
            our_rev_mode%res_restore=.FALSE.
            our_rev_mode%plain=.FALSE.
            our_rev_mode%tape=.TRUE.
            our_rev_mode%adjoint=.FALSE.
C adjoint
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_300 = integer_tape(integer_tape_pointer)
      OpenAD_Symbol_301 = 1
      DO WHILE(INT(OpenAD_Symbol_301) .LE. INT(OpenAD_Symbol_300))
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_302 = integer_tape(integer_tape_pointer)
        OpenAD_Symbol_303 = 1
        DO WHILE(INT(OpenAD_Symbol_303) .LE. INT(OpenAD_Symbol_302))
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_405 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_406 = double_tape(double_tape_pointer)
          OpenAD_Symbol_240%d = OpenAD_Symbol_240%d+FVEC(INT(OpenAD_Symb
     +ol_405))%d*OpenAD_Symbol_406
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_407 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_408 = double_tape(double_tape_pointer)
          OpenAD_Symbol_240%d = OpenAD_Symbol_240%d+FVEC(INT(OpenAD_Symb
     +ol_407))%d*OpenAD_Symbol_408
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_409 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_410 = double_tape(double_tape_pointer)
          OpenAD_Symbol_233%d = OpenAD_Symbol_233%d+FVEC(INT(OpenAD_Symb
     +ol_409))%d*OpenAD_Symbol_410
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_411 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_412 = double_tape(double_tape_pointer)
          OpenAD_Symbol_233%d = OpenAD_Symbol_233%d+FVEC(INT(OpenAD_Symb
     +ol_411))%d*OpenAD_Symbol_412
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_413 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_414 = double_tape(double_tape_pointer)
          OpenAD_Symbol_214%d = OpenAD_Symbol_214%d+FVEC(INT(OpenAD_Symb
     +ol_413))%d*OpenAD_Symbol_414
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_415 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_416 = double_tape(double_tape_pointer)
          OpenAD_Symbol_214%d = OpenAD_Symbol_214%d+FVEC(INT(OpenAD_Symb
     +ol_415))%d*OpenAD_Symbol_416
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_417 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_418 = double_tape(double_tape_pointer)
          OpenAD_Symbol_236%d = OpenAD_Symbol_236%d+FVEC(INT(OpenAD_Symb
     +ol_417))%d*OpenAD_Symbol_418
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_419 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_420 = double_tape(double_tape_pointer)
          OpenAD_Symbol_236%d = OpenAD_Symbol_236%d+FVEC(INT(OpenAD_Symb
     +ol_419))%d*OpenAD_Symbol_420
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_421 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_422 = double_tape(double_tape_pointer)
          OpenAD_Symbol_243%d = OpenAD_Symbol_243%d+FVEC(INT(OpenAD_Symb
     +ol_421))%d*OpenAD_Symbol_422
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_423 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_424 = double_tape(double_tape_pointer)
          OpenAD_Symbol_243%d = OpenAD_Symbol_243%d+FVEC(INT(OpenAD_Symb
     +ol_423))%d*OpenAD_Symbol_424
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_425 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_426 = double_tape(double_tape_pointer)
          OpenAD_Symbol_240%d = OpenAD_Symbol_240%d+FVEC(INT(OpenAD_Symb
     +ol_425))%d*OpenAD_Symbol_426
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_427 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_428 = double_tape(double_tape_pointer)
          OpenAD_Symbol_243%d = OpenAD_Symbol_243%d+FVEC(INT(OpenAD_Symb
     +ol_427))%d*OpenAD_Symbol_428
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_429 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_430 = double_tape(double_tape_pointer)
          OpenAD_Symbol_233%d = OpenAD_Symbol_233%d+FVEC(INT(OpenAD_Symb
     +ol_429))%d*OpenAD_Symbol_430
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_431 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_432 = double_tape(double_tape_pointer)
          OpenAD_Symbol_236%d = OpenAD_Symbol_236%d+FVEC(INT(OpenAD_Symb
     +ol_431))%d*OpenAD_Symbol_432
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_433 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_434 = double_tape(double_tape_pointer)
          OpenAD_Symbol_214%d = OpenAD_Symbol_214%d+FVEC(INT(OpenAD_Symb
     +ol_433))%d*OpenAD_Symbol_434
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_435 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_436 = double_tape(double_tape_pointer)
          OpenAD_Symbol_264%d = OpenAD_Symbol_264%d+FVEC(INT(OpenAD_Symb
     +ol_435))%d*OpenAD_Symbol_436
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_437 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_438 = double_tape(double_tape_pointer)
          OpenAD_Symbol_221%d = OpenAD_Symbol_221%d+FVEC(INT(OpenAD_Symb
     +ol_437))%d*OpenAD_Symbol_438
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_439 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_440 = double_tape(double_tape_pointer)
          OpenAD_Symbol_253%d = OpenAD_Symbol_253%d+FVEC(INT(OpenAD_Symb
     +ol_439))%d*OpenAD_Symbol_440
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_441 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_442 = double_tape(double_tape_pointer)
          OpenAD_Symbol_207%d = OpenAD_Symbol_207%d+FVEC(INT(OpenAD_Symb
     +ol_441))%d*OpenAD_Symbol_442
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_443 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_444 = double_tape(double_tape_pointer)
          OpenAD_Symbol_253%d = OpenAD_Symbol_253%d+FVEC(INT(OpenAD_Symb
     +ol_443))%d*OpenAD_Symbol_444
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_445 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_446 = double_tape(double_tape_pointer)
          OpenAD_Symbol_214%d = OpenAD_Symbol_214%d+FVEC(INT(OpenAD_Symb
     +ol_445))%d*OpenAD_Symbol_446
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_447 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_448 = double_tape(double_tape_pointer)
          OpenAD_Symbol_247%d = OpenAD_Symbol_247%d+FVEC(INT(OpenAD_Symb
     +ol_447))%d*OpenAD_Symbol_448
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_449 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_450 = double_tape(double_tape_pointer)
          OpenAD_Symbol_243%d = OpenAD_Symbol_243%d+FVEC(INT(OpenAD_Symb
     +ol_449))%d*OpenAD_Symbol_450
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_451 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_452 = double_tape(double_tape_pointer)
          OpenAD_Symbol_240%d = OpenAD_Symbol_240%d+FVEC(INT(OpenAD_Symb
     +ol_451))%d*OpenAD_Symbol_452
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_453 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_454 = double_tape(double_tape_pointer)
          OpenAD_Symbol_236%d = OpenAD_Symbol_236%d+FVEC(INT(OpenAD_Symb
     +ol_453))%d*OpenAD_Symbol_454
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_455 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_456 = double_tape(double_tape_pointer)
          OpenAD_Symbol_233%d = OpenAD_Symbol_233%d+FVEC(INT(OpenAD_Symb
     +ol_455))%d*OpenAD_Symbol_456
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_457 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_458 = double_tape(double_tape_pointer)
          OpenAD_Symbol_229%d = OpenAD_Symbol_229%d+FVEC(INT(OpenAD_Symb
     +ol_457))%d*OpenAD_Symbol_458
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_459 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_460 = double_tape(double_tape_pointer)
          OpenAD_Symbol_214%d = OpenAD_Symbol_214%d+FVEC(INT(OpenAD_Symb
     +ol_459))%d*OpenAD_Symbol_460
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_461 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_462 = double_tape(double_tape_pointer)
          OpenAD_Symbol_210%d = OpenAD_Symbol_210%d+FVEC(INT(OpenAD_Symb
     +ol_461))%d*OpenAD_Symbol_462
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_463 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_464 = double_tape(double_tape_pointer)
          OpenAD_Symbol_221%d = OpenAD_Symbol_221%d+FVEC(INT(OpenAD_Symb
     +ol_463))%d*OpenAD_Symbol_464
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_465 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_466 = double_tape(double_tape_pointer)
          OpenAD_Symbol_217%d = OpenAD_Symbol_217%d+FVEC(INT(OpenAD_Symb
     +ol_465))%d*OpenAD_Symbol_466
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_467 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_468 = double_tape(double_tape_pointer)
          OpenAD_Symbol_214%d = OpenAD_Symbol_214%d+FVEC(INT(OpenAD_Symb
     +ol_467))%d*OpenAD_Symbol_468
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_469 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_470 = double_tape(double_tape_pointer)
          OpenAD_Symbol_210%d = OpenAD_Symbol_210%d+FVEC(INT(OpenAD_Symb
     +ol_469))%d*OpenAD_Symbol_470
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_471 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_472 = double_tape(double_tape_pointer)
          OpenAD_Symbol_207%d = OpenAD_Symbol_207%d+FVEC(INT(OpenAD_Symb
     +ol_471))%d*OpenAD_Symbol_472
          FVEC(INT(OpenAD_Symbol_471))%d = 0.0d0
          PTL%d = PTL%d+OpenAD_Symbol_207%d
          OpenAD_Symbol_207%d = 0.0d0
          PTR%d = PTR%d+OpenAD_Symbol_210%d
          OpenAD_Symbol_210%d = 0.0d0
          P%d = P%d+OpenAD_Symbol_214%d
          OpenAD_Symbol_214%d = 0.0d0
          PTT%d = PTT%d+OpenAD_Symbol_217%d
          OpenAD_Symbol_217%d = 0.0d0
          PBR%d = PBR%d+OpenAD_Symbol_221%d
          OpenAD_Symbol_221%d = 0.0d0
          PRR%d = PRR%d+OpenAD_Symbol_229%d
          OpenAD_Symbol_229%d = 0.0d0
          PL%d = PL%d+OpenAD_Symbol_233%d
          OpenAD_Symbol_233%d = 0.0d0
          PR%d = PR%d+OpenAD_Symbol_236%d
          OpenAD_Symbol_236%d = 0.0d0
          PB%d = PB%d+OpenAD_Symbol_240%d
          OpenAD_Symbol_240%d = 0.0d0
          PT%d = PT%d+OpenAD_Symbol_243%d
          OpenAD_Symbol_243%d = 0.0d0
          PLL%d = PLL%d+OpenAD_Symbol_247%d
          OpenAD_Symbol_247%d = 0.0d0
          PBL%d = PBL%d+OpenAD_Symbol_253%d
          OpenAD_Symbol_253%d = 0.0d0
          PBB%d = PBB%d+OpenAD_Symbol_264%d
          OpenAD_Symbol_264%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_304 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_304 .ne. 0) THEN
          PTR%d = 0.0d0
          ELSE
          if (iaddr(PTR) .ne. iaddr(OpenAD_Symbol_284)) then
            OpenAD_Symbol_284%d = OpenAD_Symbol_284%d+PTR%d
            PTR%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_473 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_473))%d = X(INT(OpenAD_Symbol_473))%d+Open
     +AD_Symbol_284%d
          OpenAD_Symbol_284%d = 0.0d0
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_305 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_305 .ne. 0) THEN
          PTT%d = 0.0d0
          if (iaddr(PT) .ne. iaddr(OpenAD_Symbol_167)) then
            OpenAD_Symbol_167%d = OpenAD_Symbol_167%d+PT%d
            PT%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_404 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_404))%d = X(INT(OpenAD_Symbol_404))%d+Open
     +AD_Symbol_167%d
          OpenAD_Symbol_167%d = 0.0d0
          ELSE
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_306 = integer_tape(integer_tape_pointer)
            IF(OpenAD_Symbol_306 .ne. 0) THEN
          PT%d = 0.0d0
          if (iaddr(PTT) .ne. iaddr(OpenAD_Symbol_285)) then
            OpenAD_Symbol_285%d = OpenAD_Symbol_285%d+PTT%d
            PTT%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_474 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_474))%d = X(INT(OpenAD_Symbol_474))%d+Open
     +AD_Symbol_285%d
          OpenAD_Symbol_285%d = 0.0d0
            ELSE
          if (iaddr(PTT) .ne. iaddr(OpenAD_Symbol_287)) then
            OpenAD_Symbol_287%d = OpenAD_Symbol_287%d+PTT%d
            PTT%d = 0
          end if
          if (iaddr(PT) .ne. iaddr(OpenAD_Symbol_286)) then
            OpenAD_Symbol_286%d = OpenAD_Symbol_286%d+PT%d
            PT%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_475 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_475))%d = X(INT(OpenAD_Symbol_475))%d+Open
     +AD_Symbol_286%d
          OpenAD_Symbol_286%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_476 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_476))%d = X(INT(OpenAD_Symbol_476))%d+Open
     +AD_Symbol_287%d
          OpenAD_Symbol_287%d = 0.0d0
            ENDIF
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_307 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_307 .ne. 0) THEN
          PTL%d = 0.0d0
          ELSE
          if (iaddr(PTL) .ne. iaddr(OpenAD_Symbol_288)) then
            OpenAD_Symbol_288%d = OpenAD_Symbol_288%d+PTL%d
            PTL%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_477 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_477))%d = X(INT(OpenAD_Symbol_477))%d+Open
     +AD_Symbol_288%d
          OpenAD_Symbol_288%d = 0.0d0
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_308 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_308 .ne. 0) THEN
          PRR%d = 0.0d0
          if (iaddr(PR) .ne. iaddr(OpenAD_Symbol_166)) then
            OpenAD_Symbol_166%d = OpenAD_Symbol_166%d+PR%d
            PR%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_403 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_403))%d = X(INT(OpenAD_Symbol_403))%d+Open
     +AD_Symbol_166%d
          OpenAD_Symbol_166%d = 0.0d0
          ELSE
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_309 = integer_tape(integer_tape_pointer)
            IF(OpenAD_Symbol_309 .ne. 0) THEN
          PR%d = 0.0d0
          if (iaddr(PRR) .ne. iaddr(OpenAD_Symbol_289)) then
            OpenAD_Symbol_289%d = OpenAD_Symbol_289%d+PRR%d
            PRR%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_478 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_478))%d = X(INT(OpenAD_Symbol_478))%d+Open
     +AD_Symbol_289%d
          OpenAD_Symbol_289%d = 0.0d0
            ELSE
          if (iaddr(PRR) .ne. iaddr(OpenAD_Symbol_291)) then
            OpenAD_Symbol_291%d = OpenAD_Symbol_291%d+PRR%d
            PRR%d = 0
          end if
          if (iaddr(PR) .ne. iaddr(OpenAD_Symbol_290)) then
            OpenAD_Symbol_290%d = OpenAD_Symbol_290%d+PR%d
            PR%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_479 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_479))%d = X(INT(OpenAD_Symbol_479))%d+Open
     +AD_Symbol_290%d
          OpenAD_Symbol_290%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_480 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_480))%d = X(INT(OpenAD_Symbol_480))%d+Open
     +AD_Symbol_291%d
          OpenAD_Symbol_291%d = 0.0d0
            ENDIF
          ENDIF
          if (iaddr(P) .ne. iaddr(OpenAD_Symbol_165)) then
            OpenAD_Symbol_165%d = OpenAD_Symbol_165%d+P%d
            P%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_402 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_402))%d = X(INT(OpenAD_Symbol_402))%d+Open
     +AD_Symbol_165%d
          OpenAD_Symbol_165%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_310 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_310 .ne. 0) THEN
          PL%d = 0.0d0
          if (iaddr(PLL) .ne. iaddr(OpenAD_Symbol_164)) then
            OpenAD_Symbol_164%d = OpenAD_Symbol_164%d+PLL%d
            PLL%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_401 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_401))%d = X(INT(OpenAD_Symbol_401))%d+Open
     +AD_Symbol_164%d
          OpenAD_Symbol_164%d = 0.0d0
          ELSE
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_311 = integer_tape(integer_tape_pointer)
            IF(OpenAD_Symbol_311 .ne. 0) THEN
          PLL%d = 0.0d0
          if (iaddr(PL) .ne. iaddr(OpenAD_Symbol_292)) then
            OpenAD_Symbol_292%d = OpenAD_Symbol_292%d+PL%d
            PL%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_481 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_481))%d = X(INT(OpenAD_Symbol_481))%d+Open
     +AD_Symbol_292%d
          OpenAD_Symbol_292%d = 0.0d0
            ELSE
          if (iaddr(PLL) .ne. iaddr(OpenAD_Symbol_294)) then
            OpenAD_Symbol_294%d = OpenAD_Symbol_294%d+PLL%d
            PLL%d = 0
          end if
          if (iaddr(PL) .ne. iaddr(OpenAD_Symbol_293)) then
            OpenAD_Symbol_293%d = OpenAD_Symbol_293%d+PL%d
            PL%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_482 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_482))%d = X(INT(OpenAD_Symbol_482))%d+Open
     +AD_Symbol_293%d
          OpenAD_Symbol_293%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_483 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_483))%d = X(INT(OpenAD_Symbol_483))%d+Open
     +AD_Symbol_294%d
          OpenAD_Symbol_294%d = 0.0d0
            ENDIF
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_312 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_312 .ne. 0) THEN
          PBR%d = 0.0d0
          ELSE
          if (iaddr(PBR) .ne. iaddr(OpenAD_Symbol_295)) then
            OpenAD_Symbol_295%d = OpenAD_Symbol_295%d+PBR%d
            PBR%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_484 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_484))%d = X(INT(OpenAD_Symbol_484))%d+Open
     +AD_Symbol_295%d
          OpenAD_Symbol_295%d = 0.0d0
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_313 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_313 .ne. 0) THEN
          PB%d = 0.0d0
          if (iaddr(PBB) .ne. iaddr(OpenAD_Symbol_163)) then
            OpenAD_Symbol_163%d = OpenAD_Symbol_163%d+PBB%d
            PBB%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_400 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_400))%d = X(INT(OpenAD_Symbol_400))%d+Open
     +AD_Symbol_163%d
          OpenAD_Symbol_163%d = 0.0d0
          ELSE
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_314 = integer_tape(integer_tape_pointer)
            IF(OpenAD_Symbol_314 .ne. 0) THEN
          PBB%d = 0.0d0
          if (iaddr(PB) .ne. iaddr(OpenAD_Symbol_296)) then
            OpenAD_Symbol_296%d = OpenAD_Symbol_296%d+PB%d
            PB%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_485 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_485))%d = X(INT(OpenAD_Symbol_485))%d+Open
     +AD_Symbol_296%d
          OpenAD_Symbol_296%d = 0.0d0
            ELSE
          if (iaddr(PBB) .ne. iaddr(OpenAD_Symbol_298)) then
            OpenAD_Symbol_298%d = OpenAD_Symbol_298%d+PBB%d
            PBB%d = 0
          end if
          if (iaddr(PB) .ne. iaddr(OpenAD_Symbol_297)) then
            OpenAD_Symbol_297%d = OpenAD_Symbol_297%d+PB%d
            PB%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_486 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_486))%d = X(INT(OpenAD_Symbol_486))%d+Open
     +AD_Symbol_297%d
          OpenAD_Symbol_297%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_487 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_487))%d = X(INT(OpenAD_Symbol_487))%d+Open
     +AD_Symbol_298%d
          OpenAD_Symbol_298%d = 0.0d0
            ENDIF
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_315 = integer_tape(integer_tape_pointer)
          IF(OpenAD_Symbol_315 .ne. 0) THEN
          PBL%d = 0.0d0
          ELSE
          if (iaddr(PBL) .ne. iaddr(OpenAD_Symbol_299)) then
            OpenAD_Symbol_299%d = OpenAD_Symbol_299%d+PBL%d
            PBL%d = 0
          end if
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_488 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_488))%d = X(INT(OpenAD_Symbol_488))%d+Open
     +AD_Symbol_299%d
          OpenAD_Symbol_299%d = 0.0d0
          ENDIF
          OpenAD_Symbol_303 = INT(OpenAD_Symbol_303) + 1
        END DO
        OpenAD_Symbol_301 = INT(OpenAD_Symbol_301) + 1
      END DO
            our_rev_mode%arg_store=.FALSE.
            our_rev_mode%arg_restore=.TRUE.
            our_rev_mode%res_store=.FALSE.
            our_rev_mode%res_restore=.FALSE.
            our_rev_mode%plain=.FALSE.
            our_rev_mode%tape=.TRUE.
            our_rev_mode%adjoint=.FALSE.
          end if 
C          write(*,'(A,I6,A,I6,A,I5,A,I5)')
C     +"a:AF:", theArgFStackoffset, 
C     +" AI:",theArgIStackoffset, 
C     +" DT:",double_tape_pointer, 
C     +" IT:",integer_tape_pointer
        end subroutine head
