
      MODULE all_globals_mod
      use w2f__types
      use active_module
      IMPLICIT NONE
      SAVE
C
C     **** Statements ****
C
      END MODULE
C ========== begin copyright notice ==============
C This file is part of 
C ---------------
C xaifBooster
C ---------------
C Distributed under the BSD license as follows:
C Copyright (c) 2005, The University of Chicago
C All rights reserved.
C
C Redistribution and use in source and binary forms, 
C with or without modification, are permitted provided that the following conditions are met:
C
C    - Redistributions of source code must retain the above copyright notice, 
C      this list of conditions and the following disclaimer.
C    - Redistributions in binary form must reproduce the above copyright notice, 
C      this list of conditions and the following disclaimer in the documentation 
C      and/or other materials provided with the distribution.
C    - Neither the name of The University of Chicago nor the names of its contributors 
C      may be used to endorse or promote products derived from this software without 
C      specific prior written permission.
C
C THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
C EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
C OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
C SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
C INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
C PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
C INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
C LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
C OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
C 
C General Information:
C xaifBooster is intended for the transformation of 
C numerical programs represented as xml files according 
C to the XAIF schema. It is part of the OpenAD framework. 
C The main application is automatic 
C differentiation, i.e. the generation of code for 
C the computation of derivatives. 
C The following people are the principal authors of the 
C current version: 
C 	Uwe Naumann
C	Jean Utke
C Additional contributors are: 
C	Andrew Lyons
C	Peter Fine
C
C For more details about xaifBooster and its use in OpenAD please visit:
C   http://www.mcs.anl.gov/openad
C
C This work is partially supported by:
C 	NSF-ITR grant OCE-0205590
C ========== end copyright notice ==============
       subroutine head(X,F)
          use OpenAD_tape
          use OpenAD_rev

          ! original arguments get inserted before version
          ! and declared here together with all local variables
          ! generated by xaifBooster

      use w2f__types
      use active_module
      IMPLICIT NONE
C
C     **** Global Variables & Derived Type Definitions ****
C
      REAL(w2f__8) OpenAD_Symbol_0
      REAL(w2f__8) OpenAD_Symbol_1
      REAL(w2f__8) OpenAD_Symbol_100
      REAL(w2f__8) OpenAD_Symbol_101
      REAL(w2f__8) OpenAD_Symbol_102
      REAL(w2f__8) OpenAD_Symbol_103
      REAL(w2f__8) OpenAD_Symbol_104
      REAL(w2f__8) OpenAD_Symbol_105
      REAL(w2f__8) OpenAD_Symbol_106
      REAL(w2f__8) OpenAD_Symbol_107
      REAL(w2f__8) OpenAD_Symbol_108
      REAL(w2f__8) OpenAD_Symbol_11
      REAL(w2f__8) OpenAD_Symbol_110
      REAL(w2f__8) OpenAD_Symbol_111
      REAL(w2f__8) OpenAD_Symbol_112
      REAL(w2f__8) OpenAD_Symbol_113
      REAL(w2f__8) OpenAD_Symbol_115
      REAL(w2f__8) OpenAD_Symbol_116
      REAL(w2f__8) OpenAD_Symbol_118
      REAL(w2f__8) OpenAD_Symbol_119
      REAL(w2f__8) OpenAD_Symbol_12
      REAL(w2f__8) OpenAD_Symbol_120
      REAL(w2f__8) OpenAD_Symbol_121
      REAL(w2f__8) OpenAD_Symbol_122
      REAL(w2f__8) OpenAD_Symbol_123
      REAL(w2f__8) OpenAD_Symbol_124
      REAL(w2f__8) OpenAD_Symbol_125
      REAL(w2f__8) OpenAD_Symbol_126
      REAL(w2f__8) OpenAD_Symbol_127
      REAL(w2f__8) OpenAD_Symbol_128
      REAL(w2f__8) OpenAD_Symbol_129
      REAL(w2f__8) OpenAD_Symbol_130
      REAL(w2f__8) OpenAD_Symbol_131
      REAL(w2f__8) OpenAD_Symbol_133
      REAL(w2f__8) OpenAD_Symbol_134
      REAL(w2f__8) OpenAD_Symbol_135
      REAL(w2f__8) OpenAD_Symbol_136
      REAL(w2f__8) OpenAD_Symbol_138
      REAL(w2f__8) OpenAD_Symbol_139
      REAL(w2f__8) OpenAD_Symbol_14
      REAL(w2f__8) OpenAD_Symbol_141
      REAL(w2f__8) OpenAD_Symbol_142
      REAL(w2f__8) OpenAD_Symbol_143
      REAL(w2f__8) OpenAD_Symbol_145
      REAL(w2f__8) OpenAD_Symbol_146
      REAL(w2f__8) OpenAD_Symbol_147
      REAL(w2f__8) OpenAD_Symbol_148
      REAL(w2f__8) OpenAD_Symbol_149
      REAL(w2f__8) OpenAD_Symbol_150
      REAL(w2f__8) OpenAD_Symbol_151
      REAL(w2f__8) OpenAD_Symbol_152
      REAL(w2f__8) OpenAD_Symbol_154
      REAL(w2f__8) OpenAD_Symbol_155
      REAL(w2f__8) OpenAD_Symbol_157
      REAL(w2f__8) OpenAD_Symbol_159
      REAL(w2f__8) OpenAD_Symbol_16
      REAL(w2f__8) OpenAD_Symbol_160
      REAL(w2f__8) OpenAD_Symbol_162
      REAL(w2f__8) OpenAD_Symbol_163
      REAL(w2f__8) OpenAD_Symbol_164
      REAL(w2f__8) OpenAD_Symbol_165
      REAL(w2f__8) OpenAD_Symbol_166
      REAL(w2f__8) OpenAD_Symbol_167
      REAL(w2f__8) OpenAD_Symbol_169
      REAL(w2f__8) OpenAD_Symbol_17
      REAL(w2f__8) OpenAD_Symbol_170
      REAL(w2f__8) OpenAD_Symbol_171
      REAL(w2f__8) OpenAD_Symbol_172
      REAL(w2f__8) OpenAD_Symbol_173
      REAL(w2f__8) OpenAD_Symbol_174
      REAL(w2f__8) OpenAD_Symbol_175
      REAL(w2f__8) OpenAD_Symbol_176
      REAL(w2f__8) OpenAD_Symbol_177
      REAL(w2f__8) OpenAD_Symbol_178
      REAL(w2f__8) OpenAD_Symbol_179
      REAL(w2f__8) OpenAD_Symbol_180
      REAL(w2f__8) OpenAD_Symbol_181
      REAL(w2f__8) OpenAD_Symbol_182
      REAL(w2f__8) OpenAD_Symbol_183
      REAL(w2f__8) OpenAD_Symbol_184
      REAL(w2f__8) OpenAD_Symbol_185
      REAL(w2f__8) OpenAD_Symbol_186
      REAL(w2f__8) OpenAD_Symbol_187
      REAL(w2f__8) OpenAD_Symbol_188
      REAL(w2f__8) OpenAD_Symbol_189
      REAL(w2f__8) OpenAD_Symbol_19
      REAL(w2f__8) OpenAD_Symbol_190
      REAL(w2f__8) OpenAD_Symbol_191
      REAL(w2f__8) OpenAD_Symbol_192
      REAL(w2f__8) OpenAD_Symbol_193
      REAL(w2f__8) OpenAD_Symbol_194
      REAL(w2f__8) OpenAD_Symbol_195
      REAL(w2f__8) OpenAD_Symbol_196
      REAL(w2f__8) OpenAD_Symbol_197
      REAL(w2f__8) OpenAD_Symbol_198
      type(active) :: OpenAD_Symbol_199
      REAL(w2f__8) OpenAD_Symbol_2
      REAL(w2f__8) OpenAD_Symbol_20
      REAL(w2f__8) OpenAD_Symbol_200
      REAL(w2f__8) OpenAD_Symbol_201
      REAL(w2f__8) OpenAD_Symbol_202
      REAL(w2f__8) OpenAD_Symbol_203
      REAL(w2f__8) OpenAD_Symbol_204
      REAL(w2f__8) OpenAD_Symbol_205
      REAL(w2f__8) OpenAD_Symbol_206
      REAL(w2f__8) OpenAD_Symbol_207
      REAL(w2f__8) OpenAD_Symbol_208
      REAL(w2f__8) OpenAD_Symbol_209
      REAL(w2f__8) OpenAD_Symbol_21
      REAL(w2f__8) OpenAD_Symbol_210
      REAL(w2f__8) OpenAD_Symbol_211
      REAL(w2f__8) OpenAD_Symbol_212
      type(active) :: OpenAD_Symbol_213
      REAL(w2f__8) OpenAD_Symbol_214
      REAL(w2f__8) OpenAD_Symbol_215
      REAL(w2f__8) OpenAD_Symbol_216
      REAL(w2f__8) OpenAD_Symbol_217
      REAL(w2f__8) OpenAD_Symbol_218
      REAL(w2f__8) OpenAD_Symbol_219
      REAL(w2f__8) OpenAD_Symbol_22
      REAL(w2f__8) OpenAD_Symbol_220
      REAL(w2f__8) OpenAD_Symbol_221
      REAL(w2f__8) OpenAD_Symbol_222
      REAL(w2f__8) OpenAD_Symbol_223
      REAL(w2f__8) OpenAD_Symbol_224
      REAL(w2f__8) OpenAD_Symbol_225
      REAL(w2f__8) OpenAD_Symbol_226
      REAL(w2f__8) OpenAD_Symbol_227
      REAL(w2f__8) OpenAD_Symbol_228
      REAL(w2f__8) OpenAD_Symbol_229
      REAL(w2f__8) OpenAD_Symbol_23
      REAL(w2f__8) OpenAD_Symbol_230
      REAL(w2f__8) OpenAD_Symbol_231
      REAL(w2f__8) OpenAD_Symbol_232
      REAL(w2f__8) OpenAD_Symbol_233
      REAL(w2f__8) OpenAD_Symbol_234
      REAL(w2f__8) OpenAD_Symbol_235
      REAL(w2f__8) OpenAD_Symbol_236
      type(active) :: OpenAD_Symbol_237
      REAL(w2f__8) OpenAD_Symbol_238
      REAL(w2f__8) OpenAD_Symbol_239
      REAL(w2f__8) OpenAD_Symbol_24
      REAL(w2f__8) OpenAD_Symbol_240
      REAL(w2f__8) OpenAD_Symbol_241
      REAL(w2f__8) OpenAD_Symbol_242
      REAL(w2f__8) OpenAD_Symbol_243
      REAL(w2f__8) OpenAD_Symbol_244
      REAL(w2f__8) OpenAD_Symbol_245
      REAL(w2f__8) OpenAD_Symbol_246
      REAL(w2f__8) OpenAD_Symbol_247
      type(active) :: OpenAD_Symbol_248
      REAL(w2f__8) OpenAD_Symbol_249
      REAL(w2f__8) OpenAD_Symbol_250
      REAL(w2f__8) OpenAD_Symbol_251
      REAL(w2f__8) OpenAD_Symbol_252
      REAL(w2f__8) OpenAD_Symbol_253
      REAL(w2f__8) OpenAD_Symbol_254
      REAL(w2f__8) OpenAD_Symbol_255
      REAL(w2f__8) OpenAD_Symbol_256
      REAL(w2f__8) OpenAD_Symbol_257
      REAL(w2f__8) OpenAD_Symbol_258
      REAL(w2f__8) OpenAD_Symbol_259
      REAL(w2f__8) OpenAD_Symbol_26
      REAL(w2f__8) OpenAD_Symbol_260
      REAL(w2f__8) OpenAD_Symbol_261
      type(active) :: OpenAD_Symbol_262
      INTEGER(w2f__i8) OpenAD_Symbol_263
      INTEGER(w2f__i8) OpenAD_Symbol_264
      INTEGER(w2f__i8) OpenAD_Symbol_265
      INTEGER(w2f__i8) OpenAD_Symbol_266
      INTEGER(w2f__i8) OpenAD_Symbol_267
      INTEGER(w2f__i8) OpenAD_Symbol_268
      REAL(w2f__8) OpenAD_Symbol_27
      REAL(w2f__8) OpenAD_Symbol_28
      REAL(w2f__8) OpenAD_Symbol_29
      REAL(w2f__8) OpenAD_Symbol_30
      REAL(w2f__8) OpenAD_Symbol_31
      REAL(w2f__8) OpenAD_Symbol_32
      REAL(w2f__8) OpenAD_Symbol_33
      REAL(w2f__8) OpenAD_Symbol_34
      REAL(w2f__8) OpenAD_Symbol_35
      REAL(w2f__8) OpenAD_Symbol_36
      REAL(w2f__8) OpenAD_Symbol_37
      REAL(w2f__8) OpenAD_Symbol_38
      REAL(w2f__8) OpenAD_Symbol_39
      REAL(w2f__8) OpenAD_Symbol_4
      REAL(w2f__8) OpenAD_Symbol_41
      REAL(w2f__8) OpenAD_Symbol_42
      REAL(w2f__8) OpenAD_Symbol_43
      REAL(w2f__8) OpenAD_Symbol_44
      REAL(w2f__8) OpenAD_Symbol_46
      REAL(w2f__8) OpenAD_Symbol_47
      REAL(w2f__8) OpenAD_Symbol_49
      REAL(w2f__8) OpenAD_Symbol_5
      REAL(w2f__8) OpenAD_Symbol_50
      REAL(w2f__8) OpenAD_Symbol_51
      REAL(w2f__8) OpenAD_Symbol_52
      REAL(w2f__8) OpenAD_Symbol_53
      REAL(w2f__8) OpenAD_Symbol_54
      REAL(w2f__8) OpenAD_Symbol_55
      REAL(w2f__8) OpenAD_Symbol_56
      REAL(w2f__8) OpenAD_Symbol_57
      REAL(w2f__8) OpenAD_Symbol_58
      REAL(w2f__8) OpenAD_Symbol_59
      REAL(w2f__8) OpenAD_Symbol_6
      REAL(w2f__8) OpenAD_Symbol_60
      REAL(w2f__8) OpenAD_Symbol_61
      REAL(w2f__8) OpenAD_Symbol_62
      REAL(w2f__8) OpenAD_Symbol_64
      REAL(w2f__8) OpenAD_Symbol_65
      REAL(w2f__8) OpenAD_Symbol_66
      REAL(w2f__8) OpenAD_Symbol_67
      REAL(w2f__8) OpenAD_Symbol_69
      REAL(w2f__8) OpenAD_Symbol_7
      REAL(w2f__8) OpenAD_Symbol_70
      REAL(w2f__8) OpenAD_Symbol_72
      REAL(w2f__8) OpenAD_Symbol_73
      REAL(w2f__8) OpenAD_Symbol_74
      REAL(w2f__8) OpenAD_Symbol_75
      REAL(w2f__8) OpenAD_Symbol_76
      REAL(w2f__8) OpenAD_Symbol_77
      REAL(w2f__8) OpenAD_Symbol_78
      REAL(w2f__8) OpenAD_Symbol_79
      REAL(w2f__8) OpenAD_Symbol_8
      REAL(w2f__8) OpenAD_Symbol_80
      REAL(w2f__8) OpenAD_Symbol_81
      REAL(w2f__8) OpenAD_Symbol_82
      REAL(w2f__8) OpenAD_Symbol_83
      REAL(w2f__8) OpenAD_Symbol_85
      REAL(w2f__8) OpenAD_Symbol_86
      REAL(w2f__8) OpenAD_Symbol_87
      REAL(w2f__8) OpenAD_Symbol_88
      REAL(w2f__8) OpenAD_Symbol_9
      REAL(w2f__8) OpenAD_Symbol_90
      REAL(w2f__8) OpenAD_Symbol_91
      REAL(w2f__8) OpenAD_Symbol_93
      REAL(w2f__8) OpenAD_Symbol_94
      REAL(w2f__8) OpenAD_Symbol_95
      REAL(w2f__8) OpenAD_Symbol_97
      REAL(w2f__8) OpenAD_Symbol_98
      REAL(w2f__8) OpenAD_Symbol_99
C
C     **** Parameters and Result ****
C
      type(active) :: X(1 : 9)
      type(active) :: F(1 : 7)
C
C     **** Local Variables and Functions ****
C
      REAL(w2f__8) H
      INTEGER(w2f__i4) I
      INTEGER(w2f__i8) OpenAD_Symbol_269
      INTEGER(w2f__i8) OpenAD_Symbol_270
      INTEGER(w2f__i8) OpenAD_Symbol_271
      INTEGER(w2f__i8) OpenAD_Symbol_272
      INTEGER(w2f__i8) OpenAD_Symbol_273
      INTEGER(w2f__i8) OpenAD_Symbol_274
      INTEGER(w2f__i8) OpenAD_Symbol_275
      INTEGER(w2f__i8) OpenAD_Symbol_276
      INTEGER(w2f__i8) OpenAD_Symbol_277
      INTEGER(w2f__i8) OpenAD_Symbol_278
      INTEGER(w2f__i8) OpenAD_Symbol_279
      INTEGER(w2f__i8) OpenAD_Symbol_280
      REAL(w2f__8) OpenAD_Symbol_281
      REAL(w2f__8) OpenAD_Symbol_282
      REAL(w2f__8) OpenAD_Symbol_283
      REAL(w2f__8) OpenAD_Symbol_284
      REAL(w2f__8) OpenAD_Symbol_285
      REAL(w2f__8) OpenAD_Symbol_286
      REAL(w2f__8) OpenAD_Symbol_287
      REAL(w2f__8) OpenAD_Symbol_288
      REAL(w2f__8) OpenAD_Symbol_289
      REAL(w2f__8) OpenAD_Symbol_290
      INTEGER(w2f__i8) OpenAD_Symbol_291
      INTEGER(w2f__i8) OpenAD_Symbol_292
      REAL(w2f__8) OpenAD_Symbol_293
      INTEGER(w2f__i8) OpenAD_Symbol_294
      REAL(w2f__8) OpenAD_Symbol_295
      INTEGER(w2f__i8) OpenAD_Symbol_296
      INTEGER(w2f__i8) OpenAD_Symbol_297
      REAL(w2f__8) OpenAD_Symbol_298
      INTEGER(w2f__i8) OpenAD_Symbol_299
      REAL(w2f__8) OpenAD_Symbol_300
      INTEGER(w2f__i8) OpenAD_Symbol_301
      REAL(w2f__8) OpenAD_Symbol_302
      INTEGER(w2f__i8) OpenAD_Symbol_303
      INTEGER(w2f__i8) OpenAD_Symbol_304
      REAL(w2f__8) OpenAD_Symbol_305
      INTEGER(w2f__i8) OpenAD_Symbol_306
      REAL(w2f__8) OpenAD_Symbol_307
      INTEGER(w2f__i8) OpenAD_Symbol_308
      INTEGER(w2f__i8) OpenAD_Symbol_309
      REAL(w2f__8) OpenAD_Symbol_310
      INTEGER(w2f__i8) OpenAD_Symbol_311
      INTEGER(w2f__i8) OpenAD_Symbol_312
      REAL(w2f__8) OpenAD_Symbol_313
      INTEGER(w2f__i8) OpenAD_Symbol_314
      INTEGER(w2f__i8) OpenAD_Symbol_315
      REAL(w2f__8) OpenAD_Symbol_316
      INTEGER(w2f__i8) OpenAD_Symbol_317
      REAL(w2f__8) OpenAD_Symbol_318
      INTEGER(w2f__i8) OpenAD_Symbol_319
      INTEGER(w2f__i8) OpenAD_Symbol_320
      REAL(w2f__8) OpenAD_Symbol_321
      INTEGER(w2f__i8) OpenAD_Symbol_322
      REAL(w2f__8) OpenAD_Symbol_323
      INTEGER(w2f__i8) OpenAD_Symbol_324
      INTEGER(w2f__i8) OpenAD_Symbol_325
      REAL(w2f__8) OpenAD_Symbol_326
      INTEGER(w2f__i8) OpenAD_Symbol_327
      INTEGER(w2f__i8) OpenAD_Symbol_328
      REAL(w2f__8) OpenAD_Symbol_329
      INTEGER(w2f__i8) OpenAD_Symbol_330
      REAL(w2f__8) OpenAD_Symbol_331
      INTEGER(w2f__i8) OpenAD_Symbol_332
      INTEGER(w2f__i8) OpenAD_Symbol_333
      REAL(w2f__8) OpenAD_Symbol_334
      INTEGER(w2f__i8) OpenAD_Symbol_335
      REAL(w2f__8) OpenAD_Symbol_336
      REAL(w2f__8) OpenAD_Symbol_337
      REAL(w2f__8) OpenAD_Symbol_338
      REAL(w2f__8) OpenAD_Symbol_339
      REAL(w2f__8) OpenAD_Symbol_340
      REAL(w2f__8) OpenAD_Symbol_341
      REAL(w2f__8) OpenAD_Symbol_342
      REAL(w2f__8) OpenAD_Symbol_343
      REAL(w2f__8) OpenAD_Symbol_344
      REAL(w2f__8) OpenAD_Symbol_345
      REAL(w2f__8) OpenAD_Symbol_346
      REAL(w2f__8) OpenAD_Symbol_347
      REAL(w2f__8) OpenAD_Symbol_348
C
C     **** Top Level Pragmas ****
C
C$OPENAD INDEPENDENT(X)
C$OPENAD DEPENDENT(F)
C
C     **** Statements ****
C

          integer iaddr
          external iaddr

         if (our_rev_mode%plain) then
! original function
C$OPENAD XXX Template ad_template.f
      H = 2.5D-01
      F(1)%v = (X(1)%v*(-2.0D00)+((X(8)%v*H*H)/1.2D+01)*(EXP(X(1)%v/(X(1
     +)%v*X(9)%v+1.0D00))*1.0D+01+1.0D00))
      F(2)%v = (X(1)%v+EXP(X(1)%v/(X(1)%v*X(9)%v+1.0D00))*((X(8)%v*H*H)/
     +1.2D+01))
      DO I = 2, 6, 1
        F(INT(I+(-1)))%v = (X(I)%v+F(I+(-1))%v+EXP(X(I)%v/(X(I)%v*X(9)%v
     ++1.0D00))*((X(8)%v*H*H)/1.2D+01))
        F(INT(I))%v = (EXP(X(I)%v/(X(I)%v*X(9)%v+1.0D00))*((X(8)%v*H*H)/
     +1.20000004768371582031D00)+F(I)%v-X(I)%v*2.0D00)
        F(INT(I+1))%v = (X(I)%v+EXP(X(I)%v/(X(I)%v*X(9)%v+1.0D00))*((X(8
     +)%v*H*H)/1.2D+01))
      END DO
      F(6)%v = (X(7)%v+F(6)%v+EXP(X(7)%v/(X(7)%v*X(9)%v+1.0D00))*((X(8)%
     +v*H*H)/1.2D+01))
      F(7)%v = (F(7)%v-X(7)%v*2.0D00)
      F(7)%v = (F(7)%v+((X(8)%v*H*H)/1.2D+01)*(EXP(X(7)%v/(X(7)%v*X(9)%v
     ++1.0D00))*1.0D+01+1.0D00))
      RETURN
          end if
          if (our_rev_mode%tape) then
! taping
C$OPENAD XXX Template ad_template.f
      H = 2.5D-01
      OpenAD_Symbol_11 = (H * H)
      OpenAD_Symbol_8 = (X(8)%v*OpenAD_Symbol_11)
      OpenAD_Symbol_4 = (OpenAD_Symbol_8 / 1.2D+01)
      OpenAD_Symbol_21 = (X(1)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_19 = (X(1)%v/OpenAD_Symbol_21)
      OpenAD_Symbol_16 = EXP(OpenAD_Symbol_19)
      OpenAD_Symbol_5 = (OpenAD_Symbol_16 * 1.0D+01 + 1.0D00)
      F(1)%v = (X(1)%v*(-2.0D00)+OpenAD_Symbol_4*OpenAD_Symbol_5)
      OpenAD_Symbol_2 = (-2.0D00)
      OpenAD_Symbol_0 = 1_w2f__i8
      OpenAD_Symbol_12 = OpenAD_Symbol_11
      OpenAD_Symbol_9 = (INT(1_w2f__i8) / 1.2D+01)
      OpenAD_Symbol_6 = OpenAD_Symbol_5
      OpenAD_Symbol_22 = (INT(1_w2f__i8) / OpenAD_Symbol_21)
      OpenAD_Symbol_26 = X(9)%v
      OpenAD_Symbol_27 = X(1)%v
      OpenAD_Symbol_24 = 1_w2f__i8
      OpenAD_Symbol_23 = (-(X(1)%v/(OpenAD_Symbol_21*OpenAD_Symbol_21)))
      OpenAD_Symbol_20 = EXP(OpenAD_Symbol_19)
      OpenAD_Symbol_17 = 1.0D+01
      OpenAD_Symbol_14 = 1_w2f__i8
      OpenAD_Symbol_7 = OpenAD_Symbol_4
      OpenAD_Symbol_1 = 1_w2f__i8
      OpenAD_Symbol_36 = (X(1)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_34 = (X(1)%v/OpenAD_Symbol_36)
      OpenAD_Symbol_30 = EXP(OpenAD_Symbol_34)
      OpenAD_Symbol_46 = (H * H)
      OpenAD_Symbol_43 = (X(8)%v*OpenAD_Symbol_46)
      OpenAD_Symbol_31 = (OpenAD_Symbol_43 / 1.2D+01)
      F(2)%v = (X(1)%v+OpenAD_Symbol_30*OpenAD_Symbol_31)
      OpenAD_Symbol_28 = 1_w2f__i8
      OpenAD_Symbol_37 = (INT(1_w2f__i8) / OpenAD_Symbol_36)
      OpenAD_Symbol_41 = X(9)%v
      OpenAD_Symbol_42 = X(1)%v
      OpenAD_Symbol_39 = 1_w2f__i8
      OpenAD_Symbol_38 = (-(X(1)%v/(OpenAD_Symbol_36*OpenAD_Symbol_36)))
      OpenAD_Symbol_35 = EXP(OpenAD_Symbol_34)
      OpenAD_Symbol_32 = OpenAD_Symbol_31
      OpenAD_Symbol_47 = OpenAD_Symbol_46
      OpenAD_Symbol_44 = (INT(1_w2f__i8) / 1.2D+01)
      OpenAD_Symbol_33 = OpenAD_Symbol_30
      OpenAD_Symbol_29 = 1_w2f__i8
      OpenAD_Symbol_171 = (OpenAD_Symbol_6 * OpenAD_Symbol_1)
      OpenAD_Symbol_172 = (OpenAD_Symbol_7 * OpenAD_Symbol_1)
      OpenAD_Symbol_173 = (OpenAD_Symbol_32 * OpenAD_Symbol_29)
      OpenAD_Symbol_174 = (OpenAD_Symbol_33 * OpenAD_Symbol_29)
      OpenAD_Symbol_175 = (OpenAD_Symbol_14 * OpenAD_Symbol_172)
      OpenAD_Symbol_176 = (OpenAD_Symbol_17 * OpenAD_Symbol_175)
      OpenAD_Symbol_177 = (OpenAD_Symbol_35 * OpenAD_Symbol_173)
      OpenAD_Symbol_178 = (OpenAD_Symbol_37 * OpenAD_Symbol_177)
      OpenAD_Symbol_179 = (OpenAD_Symbol_38 * OpenAD_Symbol_177)
      OpenAD_Symbol_180 = (OpenAD_Symbol_20 * OpenAD_Symbol_176)
      OpenAD_Symbol_181 = (OpenAD_Symbol_22 * OpenAD_Symbol_180)
      OpenAD_Symbol_182 = (OpenAD_Symbol_23 * OpenAD_Symbol_180)
      OpenAD_Symbol_183 = (OpenAD_Symbol_44 * OpenAD_Symbol_174)
      OpenAD_Symbol_184 = (OpenAD_Symbol_39 * OpenAD_Symbol_179)
      OpenAD_Symbol_185 = (OpenAD_Symbol_41 * OpenAD_Symbol_184)
      OpenAD_Symbol_186 = (OpenAD_Symbol_42 * OpenAD_Symbol_184)
      OpenAD_Symbol_187 = (OpenAD_Symbol_24 * OpenAD_Symbol_182)
      OpenAD_Symbol_188 = (OpenAD_Symbol_26 * OpenAD_Symbol_187)
      OpenAD_Symbol_189 = (OpenAD_Symbol_27 * OpenAD_Symbol_187)
      OpenAD_Symbol_190 = (OpenAD_Symbol_9 * OpenAD_Symbol_171)
      OpenAD_Symbol_191 = (OpenAD_Symbol_47 * OpenAD_Symbol_183)
      OpenAD_Symbol_192 = (OpenAD_Symbol_12 * OpenAD_Symbol_190)
      OpenAD_Symbol_193 = (OpenAD_Symbol_2 * OpenAD_Symbol_0)
      OpenAD_Symbol_194 = OpenAD_Symbol_28
          double_tape(double_tape_pointer) = OpenAD_Symbol_178
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_181
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_185
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_186
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_188
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_189
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_191
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_192
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_193
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_194
          double_tape_pointer = double_tape_pointer+1
      OpenAD_Symbol_265 = 0_w2f__i8
      DO I = 2, 6, 1
        OpenAD_Symbol_59 = (X(I)%v*X(9)%v+1.0D00)
        OpenAD_Symbol_57 = (X(I)%v/OpenAD_Symbol_59)
        OpenAD_Symbol_53 = EXP(OpenAD_Symbol_57)
        OpenAD_Symbol_69 = (H * H)
        OpenAD_Symbol_66 = (X(8)%v*OpenAD_Symbol_69)
        OpenAD_Symbol_54 = (OpenAD_Symbol_66 / 1.2D+01)
        F(INT(I+(-1)))%v = (X(I)%v+F(I+(-1))%v+OpenAD_Symbol_53*OpenAD_S
     +ymbol_54)
        OpenAD_Symbol_51 = 1_w2f__i8
        OpenAD_Symbol_52 = 1_w2f__i8
        OpenAD_Symbol_49 = 1_w2f__i8
        OpenAD_Symbol_60 = (INT(1_w2f__i8) / OpenAD_Symbol_59)
        OpenAD_Symbol_64 = X(9)%v
        OpenAD_Symbol_65 = X(I)%v
        OpenAD_Symbol_62 = 1_w2f__i8
        OpenAD_Symbol_61 = (-(X(I)%v/(OpenAD_Symbol_59*OpenAD_Symbol_59)
     +))
        OpenAD_Symbol_58 = EXP(OpenAD_Symbol_57)
        OpenAD_Symbol_55 = OpenAD_Symbol_54
        OpenAD_Symbol_70 = OpenAD_Symbol_69
        OpenAD_Symbol_67 = (INT(1_w2f__i8) / 1.2D+01)
        OpenAD_Symbol_56 = OpenAD_Symbol_53
        OpenAD_Symbol_50 = 1_w2f__i8
        OpenAD_Symbol_195 = (OpenAD_Symbol_55 * OpenAD_Symbol_50)
        OpenAD_Symbol_196 = (OpenAD_Symbol_56 * OpenAD_Symbol_50)
        OpenAD_Symbol_197 = (OpenAD_Symbol_51 * OpenAD_Symbol_49)
        OpenAD_Symbol_198 = (OpenAD_Symbol_52 * OpenAD_Symbol_49)
        OpenAD_Symbol_200 = (OpenAD_Symbol_58 * OpenAD_Symbol_195)
        OpenAD_Symbol_201 = (OpenAD_Symbol_60 * OpenAD_Symbol_200)
        OpenAD_Symbol_202 = (OpenAD_Symbol_61 * OpenAD_Symbol_200)
        OpenAD_Symbol_203 = (OpenAD_Symbol_67 * OpenAD_Symbol_196)
        OpenAD_Symbol_204 = (OpenAD_Symbol_62 * OpenAD_Symbol_202)
        OpenAD_Symbol_205 = (OpenAD_Symbol_64 * OpenAD_Symbol_204)
        OpenAD_Symbol_206 = (OpenAD_Symbol_65 * OpenAD_Symbol_204)
        OpenAD_Symbol_207 = (OpenAD_Symbol_70 * OpenAD_Symbol_203)
        OpenAD_Symbol_269 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_269
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_197
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_270 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_270
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_198
          double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_271 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_271
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_201
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_272 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_272
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_205
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_273 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_273
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_206
          double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_274 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_274
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_207
          double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_275 = (I + INT((-1_w2f__i8)))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_275
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_80 = (X(I)%v*X(9)%v+1.0D00)
        OpenAD_Symbol_78 = (X(I)%v/OpenAD_Symbol_80)
        OpenAD_Symbol_74 = EXP(OpenAD_Symbol_78)
        OpenAD_Symbol_90 = (H * H)
        OpenAD_Symbol_87 = (X(8)%v*OpenAD_Symbol_90)
        OpenAD_Symbol_75 = (OpenAD_Symbol_87 /  1.20000004768371582031D0
     +0)
        F(INT(I))%v = (OpenAD_Symbol_74*OpenAD_Symbol_75+F(I)%v-X(I)%v*2
     +.0D00)
        OpenAD_Symbol_81 = (INT(1_w2f__i8) / OpenAD_Symbol_80)
        OpenAD_Symbol_85 = X(9)%v
        OpenAD_Symbol_86 = X(I)%v
        OpenAD_Symbol_83 = 1_w2f__i8
        OpenAD_Symbol_82 = (-(X(I)%v/(OpenAD_Symbol_80*OpenAD_Symbol_80)
     +))
        OpenAD_Symbol_79 = EXP(OpenAD_Symbol_78)
        OpenAD_Symbol_76 = OpenAD_Symbol_75
        OpenAD_Symbol_91 = OpenAD_Symbol_90
        OpenAD_Symbol_88 = (INT(1_w2f__i8) / 1.20000004768371582031D00)
        OpenAD_Symbol_77 = OpenAD_Symbol_74
        OpenAD_Symbol_72 = 1_w2f__i8
        OpenAD_Symbol_93 = 1_w2f__i8
        OpenAD_Symbol_95 = 2.0D00
        OpenAD_Symbol_94 = (-1_w2f__i8)
        OpenAD_Symbol_73 = 1_w2f__i8
        OpenAD_Symbol_105 = (X(I)%v*X(9)%v+1.0D00)
        OpenAD_Symbol_103 = (X(I)%v/OpenAD_Symbol_105)
        OpenAD_Symbol_99 = EXP(OpenAD_Symbol_103)
        OpenAD_Symbol_115 = (H * H)
        OpenAD_Symbol_112 = (X(8)%v*OpenAD_Symbol_115)
        OpenAD_Symbol_100 = (OpenAD_Symbol_112 / 1.2D+01)
        F(INT(I+1))%v = (X(I)%v+OpenAD_Symbol_99*OpenAD_Symbol_100)
        OpenAD_Symbol_97 = 1_w2f__i8
        OpenAD_Symbol_106 = (INT(1_w2f__i8) / OpenAD_Symbol_105)
        OpenAD_Symbol_110 = X(9)%v
        OpenAD_Symbol_111 = X(I)%v
        OpenAD_Symbol_108 = 1_w2f__i8
        OpenAD_Symbol_107 = (-(X(I)%v/(OpenAD_Symbol_105*OpenAD_Symbol_1
     +05)))
        OpenAD_Symbol_104 = EXP(OpenAD_Symbol_103)
        OpenAD_Symbol_101 = OpenAD_Symbol_100
        OpenAD_Symbol_116 = OpenAD_Symbol_115
        OpenAD_Symbol_113 = (INT(1_w2f__i8) / 1.2D+01)
        OpenAD_Symbol_102 = OpenAD_Symbol_99
        OpenAD_Symbol_98 = 1_w2f__i8
        OpenAD_Symbol_208 = (OpenAD_Symbol_101 * OpenAD_Symbol_98)
        OpenAD_Symbol_209 = (OpenAD_Symbol_102 * OpenAD_Symbol_98)
        OpenAD_Symbol_210 = (OpenAD_Symbol_76 * OpenAD_Symbol_72)
        OpenAD_Symbol_211 = (OpenAD_Symbol_77 * OpenAD_Symbol_72)
        OpenAD_Symbol_212 = (OpenAD_Symbol_93 * OpenAD_Symbol_73)
        OpenAD_Symbol_214 = (OpenAD_Symbol_94 * OpenAD_Symbol_73)
        OpenAD_Symbol_215 = (OpenAD_Symbol_104 * OpenAD_Symbol_208)
        OpenAD_Symbol_216 = (OpenAD_Symbol_106 * OpenAD_Symbol_215)
        OpenAD_Symbol_217 = (OpenAD_Symbol_107 * OpenAD_Symbol_215)
        OpenAD_Symbol_218 = (OpenAD_Symbol_79 * OpenAD_Symbol_210)
        OpenAD_Symbol_219 = (OpenAD_Symbol_81 * OpenAD_Symbol_218)
        OpenAD_Symbol_220 = (OpenAD_Symbol_82 * OpenAD_Symbol_218)
        OpenAD_Symbol_221 = (OpenAD_Symbol_113 * OpenAD_Symbol_209)
        OpenAD_Symbol_222 = (OpenAD_Symbol_108 * OpenAD_Symbol_217)
        OpenAD_Symbol_223 = (OpenAD_Symbol_110 * OpenAD_Symbol_222)
        OpenAD_Symbol_224 = (OpenAD_Symbol_111 * OpenAD_Symbol_222)
        OpenAD_Symbol_225 = (OpenAD_Symbol_88 * OpenAD_Symbol_211)
        OpenAD_Symbol_226 = (OpenAD_Symbol_83 * OpenAD_Symbol_220)
        OpenAD_Symbol_227 = (OpenAD_Symbol_85 * OpenAD_Symbol_226)
        OpenAD_Symbol_228 = (OpenAD_Symbol_86 * OpenAD_Symbol_226)
        OpenAD_Symbol_229 = (OpenAD_Symbol_116 * OpenAD_Symbol_221)
        OpenAD_Symbol_230 = (OpenAD_Symbol_95 * OpenAD_Symbol_214)
        OpenAD_Symbol_231 = (OpenAD_Symbol_91 * OpenAD_Symbol_225)
        OpenAD_Symbol_232 = OpenAD_Symbol_97
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_212
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_216
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_276 = (I + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_276
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_219
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_223
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_277 = (I + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_277
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_224
          double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_278 = (I + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_278
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_227
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_228
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_229
          double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_279 = (I + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_279
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_230
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_231
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_232
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_280 = (I + INT(1_w2f__i8))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_280
          integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_265 = (INT(OpenAD_Symbol_265) + INT(1_w2f__i8))
      END DO
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_265
          integer_tape_pointer = integer_tape_pointer+1
      OpenAD_Symbol_128 = (X(7)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_126 = (X(7)%v/OpenAD_Symbol_128)
      OpenAD_Symbol_122 = EXP(OpenAD_Symbol_126)
      OpenAD_Symbol_138 = (H * H)
      OpenAD_Symbol_135 = (X(8)%v*OpenAD_Symbol_138)
      OpenAD_Symbol_123 = (OpenAD_Symbol_135 / 1.2D+01)
      F(6)%v = (X(7)%v+F(6)%v+OpenAD_Symbol_122*OpenAD_Symbol_123)
      OpenAD_Symbol_120 = 1_w2f__i8
      OpenAD_Symbol_121 = 1_w2f__i8
      OpenAD_Symbol_118 = 1_w2f__i8
      OpenAD_Symbol_129 = (INT(1_w2f__i8) / OpenAD_Symbol_128)
      OpenAD_Symbol_133 = X(9)%v
      OpenAD_Symbol_134 = X(7)%v
      OpenAD_Symbol_131 = 1_w2f__i8
      OpenAD_Symbol_130 = (-(X(7)%v/(OpenAD_Symbol_128*OpenAD_Symbol_128
     +)))
      OpenAD_Symbol_127 = EXP(OpenAD_Symbol_126)
      OpenAD_Symbol_124 = OpenAD_Symbol_123
      OpenAD_Symbol_139 = OpenAD_Symbol_138
      OpenAD_Symbol_136 = (INT(1_w2f__i8) / 1.2D+01)
      OpenAD_Symbol_125 = OpenAD_Symbol_122
      OpenAD_Symbol_119 = 1_w2f__i8
      OpenAD_Symbol_233 = (OpenAD_Symbol_124 * OpenAD_Symbol_119)
      OpenAD_Symbol_234 = (OpenAD_Symbol_125 * OpenAD_Symbol_119)
      OpenAD_Symbol_235 = (OpenAD_Symbol_120 * OpenAD_Symbol_118)
      OpenAD_Symbol_236 = (OpenAD_Symbol_121 * OpenAD_Symbol_118)
      OpenAD_Symbol_238 = (OpenAD_Symbol_127 * OpenAD_Symbol_233)
      OpenAD_Symbol_239 = (OpenAD_Symbol_129 * OpenAD_Symbol_238)
      OpenAD_Symbol_240 = (OpenAD_Symbol_130 * OpenAD_Symbol_238)
      OpenAD_Symbol_241 = (OpenAD_Symbol_136 * OpenAD_Symbol_234)
      OpenAD_Symbol_242 = (OpenAD_Symbol_131 * OpenAD_Symbol_240)
      OpenAD_Symbol_243 = (OpenAD_Symbol_133 * OpenAD_Symbol_242)
      OpenAD_Symbol_244 = (OpenAD_Symbol_134 * OpenAD_Symbol_242)
      OpenAD_Symbol_245 = (OpenAD_Symbol_139 * OpenAD_Symbol_241)
          double_tape(double_tape_pointer) = OpenAD_Symbol_235
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_236
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_239
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_243
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_244
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_245
          double_tape_pointer = double_tape_pointer+1
      F(7)%v = (F(7)%v-X(7)%v*2.0D00)
      OpenAD_Symbol_141 = 1_w2f__i8
      OpenAD_Symbol_143 = 2.0D00
      OpenAD_Symbol_142 = (-1_w2f__i8)
      OpenAD_Symbol_246 = (OpenAD_Symbol_143 * OpenAD_Symbol_142)
      OpenAD_Symbol_247 = OpenAD_Symbol_141
          double_tape(double_tape_pointer) = OpenAD_Symbol_246
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_247
          double_tape_pointer = double_tape_pointer+1
      OpenAD_Symbol_154 = (H * H)
      OpenAD_Symbol_151 = (X(8)%v*OpenAD_Symbol_154)
      OpenAD_Symbol_147 = (OpenAD_Symbol_151 / 1.2D+01)
      OpenAD_Symbol_164 = (X(7)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_162 = (X(7)%v/OpenAD_Symbol_164)
      OpenAD_Symbol_159 = EXP(OpenAD_Symbol_162)
      OpenAD_Symbol_148 = (OpenAD_Symbol_159 * 1.0D+01 + 1.0D00)
      F(7)%v = (F(7)%v+OpenAD_Symbol_147*OpenAD_Symbol_148)
      OpenAD_Symbol_145 = 1_w2f__i8
      OpenAD_Symbol_155 = OpenAD_Symbol_154
      OpenAD_Symbol_152 = (INT(1_w2f__i8) / 1.2D+01)
      OpenAD_Symbol_149 = OpenAD_Symbol_148
      OpenAD_Symbol_165 = (INT(1_w2f__i8) / OpenAD_Symbol_164)
      OpenAD_Symbol_169 = X(9)%v
      OpenAD_Symbol_170 = X(7)%v
      OpenAD_Symbol_167 = 1_w2f__i8
      OpenAD_Symbol_166 = (-(X(7)%v/(OpenAD_Symbol_164*OpenAD_Symbol_164
     +)))
      OpenAD_Symbol_163 = EXP(OpenAD_Symbol_162)
      OpenAD_Symbol_160 = 1.0D+01
      OpenAD_Symbol_157 = 1_w2f__i8
      OpenAD_Symbol_150 = OpenAD_Symbol_147
      OpenAD_Symbol_146 = 1_w2f__i8
      OpenAD_Symbol_249 = (OpenAD_Symbol_149 * OpenAD_Symbol_146)
      OpenAD_Symbol_250 = (OpenAD_Symbol_150 * OpenAD_Symbol_146)
      OpenAD_Symbol_251 = (OpenAD_Symbol_157 * OpenAD_Symbol_250)
      OpenAD_Symbol_252 = (OpenAD_Symbol_160 * OpenAD_Symbol_251)
      OpenAD_Symbol_253 = (OpenAD_Symbol_163 * OpenAD_Symbol_252)
      OpenAD_Symbol_254 = (OpenAD_Symbol_165 * OpenAD_Symbol_253)
      OpenAD_Symbol_255 = (OpenAD_Symbol_166 * OpenAD_Symbol_253)
      OpenAD_Symbol_256 = (OpenAD_Symbol_167 * OpenAD_Symbol_255)
      OpenAD_Symbol_257 = (OpenAD_Symbol_169 * OpenAD_Symbol_256)
      OpenAD_Symbol_258 = (OpenAD_Symbol_170 * OpenAD_Symbol_256)
      OpenAD_Symbol_259 = (OpenAD_Symbol_152 * OpenAD_Symbol_249)
      OpenAD_Symbol_260 = (OpenAD_Symbol_155 * OpenAD_Symbol_259)
      OpenAD_Symbol_261 = OpenAD_Symbol_145
          double_tape(double_tape_pointer) = OpenAD_Symbol_254
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_257
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_258
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_260
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_261
          double_tape_pointer = double_tape_pointer+1
      RETURN
          end if 
          if (our_rev_mode%adjoint) then
! adjoint
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_336 = double_tape(double_tape_pointer)
          OpenAD_Symbol_262%d = OpenAD_Symbol_262%d+F(7)%d*OpenAD_Symbol
     +_336
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_337 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(7)%d*OpenAD_Symbol_337
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_338 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(7)%d*OpenAD_Symbol_338
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_339 = double_tape(double_tape_pointer)
          X(7)%d = X(7)%d+F(7)%d*OpenAD_Symbol_339
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_340 = double_tape(double_tape_pointer)
          X(7)%d = X(7)%d+F(7)%d*OpenAD_Symbol_340
          F(7)%d = 0.0d0
          F(7)%d = F(7)%d+OpenAD_Symbol_262%d
          OpenAD_Symbol_262%d = 0.0d0
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_341 = double_tape(double_tape_pointer)
          OpenAD_Symbol_248%d = OpenAD_Symbol_248%d+F(7)%d*OpenAD_Symbol
     +_341
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_342 = double_tape(double_tape_pointer)
          X(7)%d = X(7)%d+F(7)%d*OpenAD_Symbol_342
          F(7)%d = 0.0d0
          F(7)%d = F(7)%d+OpenAD_Symbol_248%d
          OpenAD_Symbol_248%d = 0.0d0
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_343 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(6)%d*OpenAD_Symbol_343
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_344 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(6)%d*OpenAD_Symbol_344
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_345 = double_tape(double_tape_pointer)
          X(7)%d = X(7)%d+F(6)%d*OpenAD_Symbol_345
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_346 = double_tape(double_tape_pointer)
          X(7)%d = X(7)%d+F(6)%d*OpenAD_Symbol_346
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_347 = double_tape(double_tape_pointer)
          OpenAD_Symbol_237%d = OpenAD_Symbol_237%d+F(6)%d*OpenAD_Symbol
     +_347
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_348 = double_tape(double_tape_pointer)
          X(7)%d = X(7)%d+F(6)%d*OpenAD_Symbol_348
          F(6)%d = 0.0d0
          F(6)%d = F(6)%d+OpenAD_Symbol_237%d
          OpenAD_Symbol_237%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_263 = integer_tape(integer_tape_pointer)
      OpenAD_Symbol_264 = 1
      DO WHILE(INT(OpenAD_Symbol_264) .LE. INT(OpenAD_Symbol_263))
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_291 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_292 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_293 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_292))%d = X(INT(OpenAD_Symbol_292))%d+F(IN
     +T(OpenAD_Symbol_291))%d*OpenAD_Symbol_293
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_294 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_295 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(INT(OpenAD_Symbol_294))%d*OpenAD_Symbol_295
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_296 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_297 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_298 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_297))%d = X(INT(OpenAD_Symbol_297))%d+F(IN
     +T(OpenAD_Symbol_296))%d*OpenAD_Symbol_298
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_299 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_300 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(INT(OpenAD_Symbol_299))%d*OpenAD_Symbol_300
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_301 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_302 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(INT(OpenAD_Symbol_301))%d*OpenAD_Symbol_302
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_303 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_304 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_305 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_304))%d = X(INT(OpenAD_Symbol_304))%d+F(IN
     +T(OpenAD_Symbol_303))%d*OpenAD_Symbol_305
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_306 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_307 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(INT(OpenAD_Symbol_306))%d*OpenAD_Symbol_307
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_308 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_309 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_310 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_309))%d = X(INT(OpenAD_Symbol_309))%d+F(IN
     +T(OpenAD_Symbol_308))%d*OpenAD_Symbol_310
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_311 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_312 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_313 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_312))%d = X(INT(OpenAD_Symbol_312))%d+F(IN
     +T(OpenAD_Symbol_311))%d*OpenAD_Symbol_313
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_314 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_315 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_316 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_315))%d = X(INT(OpenAD_Symbol_315))%d+F(IN
     +T(OpenAD_Symbol_314))%d*OpenAD_Symbol_316
          F(INT(OpenAD_Symbol_314))%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_317 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_318 = double_tape(double_tape_pointer)
          OpenAD_Symbol_213%d = OpenAD_Symbol_213%d+F(INT(OpenAD_Symbol_
     +317))%d*OpenAD_Symbol_318
          F(INT(OpenAD_Symbol_317))%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_319 = integer_tape(integer_tape_pointer)
          F(INT(OpenAD_Symbol_319))%d = F(INT(OpenAD_Symbol_319))%d+Open
     +AD_Symbol_213%d
          OpenAD_Symbol_213%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_320 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_321 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(INT(OpenAD_Symbol_320))%d*OpenAD_Symbol_321
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_322 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_323 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(INT(OpenAD_Symbol_322))%d*OpenAD_Symbol_323
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_324 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_325 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_326 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_325))%d = X(INT(OpenAD_Symbol_325))%d+F(IN
     +T(OpenAD_Symbol_324))%d*OpenAD_Symbol_326
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_327 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_328 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_329 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_328))%d = X(INT(OpenAD_Symbol_328))%d+F(IN
     +T(OpenAD_Symbol_327))%d*OpenAD_Symbol_329
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_330 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_331 = double_tape(double_tape_pointer)
          OpenAD_Symbol_199%d = OpenAD_Symbol_199%d+F(INT(OpenAD_Symbol_
     +330))%d*OpenAD_Symbol_331
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_332 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_333 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_334 = double_tape(double_tape_pointer)
          X(INT(OpenAD_Symbol_333))%d = X(INT(OpenAD_Symbol_333))%d+F(IN
     +T(OpenAD_Symbol_332))%d*OpenAD_Symbol_334
          F(INT(OpenAD_Symbol_332))%d = 0.0d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_335 = integer_tape(integer_tape_pointer)
          F(INT(OpenAD_Symbol_335))%d = F(INT(OpenAD_Symbol_335))%d+Open
     +AD_Symbol_199%d
          OpenAD_Symbol_199%d = 0.0d0
        OpenAD_Symbol_264 = INT(OpenAD_Symbol_264) + 1
      END DO
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_281 = double_tape(double_tape_pointer)
          X(1)%d = X(1)%d+F(2)%d*OpenAD_Symbol_281
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_282 = double_tape(double_tape_pointer)
          X(1)%d = X(1)%d+F(1)%d*OpenAD_Symbol_282
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_283 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(1)%d*OpenAD_Symbol_283
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_284 = double_tape(double_tape_pointer)
          X(8)%d = X(8)%d+F(2)%d*OpenAD_Symbol_284
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_285 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(1)%d*OpenAD_Symbol_285
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_286 = double_tape(double_tape_pointer)
          X(1)%d = X(1)%d+F(1)%d*OpenAD_Symbol_286
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_287 = double_tape(double_tape_pointer)
          X(9)%d = X(9)%d+F(2)%d*OpenAD_Symbol_287
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_288 = double_tape(double_tape_pointer)
          X(1)%d = X(1)%d+F(2)%d*OpenAD_Symbol_288
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_289 = double_tape(double_tape_pointer)
          X(1)%d = X(1)%d+F(1)%d*OpenAD_Symbol_289
          F(1)%d = 0.0d0
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_290 = double_tape(double_tape_pointer)
          X(1)%d = X(1)%d+F(2)%d*OpenAD_Symbol_290
          F(2)%d = 0.0d0
          end if 
        end subroutine head
