#ifndef _XAIFBOOSTERBASICBLOCKPREACCUMULATIONTAPEADJOINT_SUBROUTINECALLALGFACTORY_INCLUDE_
#define _XAIFBOOSTERBASICBLOCKPREACCUMULATIONTAPEADJOINT_SUBROUTINECALLALGFACTORY_INCLUDE_

#include "xaifBooster/system/inc/SubroutineCallAlgFactory.hpp"
#include "xaifBooster/system/inc/SubroutineCallAlgFactory.hpp"
#include "xaifBooster/algorithms/BasicBlockPreaccumulationTapeAdjoint/inc/AlgFactoryManager.hpp"

  DERIVED_ALG_FACTORY_DECL_MACRO(SubroutineCall,xaifBooster::SubroutineCallAlgFactory,xaifBoosterBasicBlockPreaccumulationTapeAdjoint)

#endif
