#ifndef _XAIFBOOSTERCONTROLFLOWREVERSAL_CONTROLFLOWGRAPHVERTEXALGFACTORY_INCLUDE_
#define _XAIFBOOSTERCONTROLFLOWREVERSAL_CONTROLFLOWGRAPHVERTEXALGFACTORY_INCLUDE_

#include "xaifBooster/system/inc/ControlFlowGraphVertexAlgFactory.hpp"
#include "xaifBooster/algorithms/ControlFlowReversal/inc/AlgFactoryManager.hpp"


  DERIVED_ALG_FACTORY_DECL_MACRO(ControlFlowGraphVertex,xaifBooster::ControlFlowGraphVertexAlgFactory,xaifBoosterControlFlowReversal)


#endif
