#include "utils/inc/XMLParserHelper.hpp"
#include "utils/inc/LogicException.hpp"

namespace xaifBooster { 

#ifndef XMLPARSERHELPER_INITIALIZATION
#define XMLPARSERHELPER_INITIALIZATION(x)  \
  my##x##_p(0)
#else
#error macro name for XMLPARSERHELPER_INITIALIZATION already in use
#endif

#ifndef XMLPARSERHELPER_DEFINITION
#define XMLPARSERHELPER_DEFINITION(x)  \
  void \
  XMLParserHelper::set##x(x& whatToSet){ \
    if( my##x##_p ) \
      THROW_LOGICEXCEPTION_MACRO("XMLParserHelper::set" << #x << " item already set"); \
    my##x##_p=&whatToSet; \
  } \
  x& \
  XMLParserHelper::get##x() const { \
    if(! my##x##_p ) \
      THROW_LOGICEXCEPTION_MACRO("XMLParserHelper::get" << #x << " item not set"); \
    return *my##x##_p; \
  }
#else
#error macro name for XMLPARSERHELPER_DEFINITION already in use
#endif

  XMLParserHelper::XMLParserHelper() :
    XMLPARSERHELPER_INITIALIZATION(AliasActivity),
    XMLPARSERHELPER_INITIALIZATION(AliasActivityMap),
    XMLPARSERHELPER_INITIALIZATION(ArrayAccess),
    XMLPARSERHELPER_INITIALIZATION(Assignment),
    XMLPARSERHELPER_INITIALIZATION(BaseVariableReference),
    XMLPARSERHELPER_INITIALIZATION(BaseVariableReferenceEdge),
    XMLPARSERHELPER_INITIALIZATION(BasicBlock),
    XMLPARSERHELPER_INITIALIZATION(CallGraph),
    XMLPARSERHELPER_INITIALIZATION(Condition),
    XMLPARSERHELPER_INITIALIZATION(ControlFlowGraph),
    XMLPARSERHELPER_INITIALIZATION(Expression),
    XMLPARSERHELPER_INITIALIZATION(ExpressionEdge),
    XMLPARSERHELPER_INITIALIZATION(ForLoop),
    XMLPARSERHELPER_INITIALIZATION(IfStatement),
    XMLPARSERHELPER_INITIALIZATION(Initialization),
    XMLPARSERHELPER_INITIALIZATION(PostLoop),
    XMLPARSERHELPER_INITIALIZATION(PreLoop),
    XMLPARSERHELPER_INITIALIZATION(Scope),
    XMLPARSERHELPER_INITIALIZATION(Scopes),
    XMLPARSERHELPER_INITIALIZATION(SubroutineCall),
    XMLPARSERHELPER_INITIALIZATION(SymbolTable),
    XMLPARSERHELPER_INITIALIZATION(Update)
  {} // end of   XMLParserHelper::XMLParserHelper

  XMLPARSERHELPER_DEFINITION(AliasActivity)
  XMLPARSERHELPER_DEFINITION(AliasActivityMap)
  XMLPARSERHELPER_DEFINITION(ArrayAccess)
  XMLPARSERHELPER_DEFINITION(Assignment)
  XMLPARSERHELPER_DEFINITION(BaseVariableReference)
  XMLPARSERHELPER_DEFINITION(BaseVariableReferenceEdge)
  XMLPARSERHELPER_DEFINITION(BasicBlock)
  XMLPARSERHELPER_DEFINITION(CallGraph)
  XMLPARSERHELPER_DEFINITION(Condition)
  XMLPARSERHELPER_DEFINITION(ControlFlowGraph)
  XMLPARSERHELPER_DEFINITION(Expression)
  XMLPARSERHELPER_DEFINITION(ExpressionEdge)
  XMLPARSERHELPER_DEFINITION(ForLoop)
  XMLPARSERHELPER_DEFINITION(IfStatement)
  XMLPARSERHELPER_DEFINITION(Initialization)
  XMLPARSERHELPER_DEFINITION(PostLoop)
  XMLPARSERHELPER_DEFINITION(PreLoop)
  XMLPARSERHELPER_DEFINITION(Scope)
  XMLPARSERHELPER_DEFINITION(Scopes)
  XMLPARSERHELPER_DEFINITION(SubroutineCall)
  XMLPARSERHELPER_DEFINITION(SymbolTable)
  XMLPARSERHELPER_DEFINITION(Update)

} // end of namespace

