obj test doc clean:
	cd CrossCountryInterface && $(MAKE) $@
	cd InlinableXMLRepresentation && $(MAKE) $@
	cd Linearization && $(MAKE) $@
	cd BasicBlockPreaccumulation && $(MAKE) $@
	cd MemOpsTradeoffPreaccumulation && $(MAKE) $@
	cd BasicBlockPreaccumulationTape && $(MAKE) $@

.PHONY: obj test doc clean
