obj test doc clean:
	cd CrossCountryInterface && $(MAKE) $@
	cd InlinableXMLRepresentation && $(MAKE) $@
	cd CodeReplacement && $(MAKE) $@
	cd DerivativePropagator && $(MAKE) $@
	cd Linearization && $(MAKE) $@
	cd BasicBlockPreaccumulation && $(MAKE) $@
	cd MemOpsTradeoffPreaccumulation && $(MAKE) $@
	cd BasicBlockPreaccumulationTape && $(MAKE) $@
	cd BasicBlockPreaccumulationTapeAdjoint && $(MAKE) $@
	cd ControlFlowReversal && $(MAKE) $@
	cd BasicBlockPreaccumulationReverse && $(MAKE) $@

.PHONY: obj test doc clean
